MisskeyIO/misskey

src/client/pages/instance/users.vue

Fix Merge defect

---

src/client/app/common/views/components/emoji.vue
src/client/app/common/views/components/reaction-icon.vue
src/client/app/common/views/components/reaction-picker.vue
src/client/app/common/views/components/reactions-viewer.details.vue
src/client/app/common/views/components/reactions-viewer.reaction.vue
src/client/app/common/views/deck/deck.notification.vue
src/client/app/desktop/views/components/notifications.vue
src/client/app/mobile/views/components/notification-preview.vue
src/client/app/mobile/views/components/notification.vue
src/client/app/store.ts

Fix display of custom emojis reactions

---

packages/backend/src/server/ServerService.ts

Add x-worker-host header

---

packages/backend/src/@types/fastify.d.ts
packages/backend/src/server/web/ClientServerService.ts

- CSPのscript-srcにnonceを追加
- CSPにworker-srcを追加
- Cloudflareが挿入するJavaScriptのうちの一部はnonceの自動パースに対応しているため (Report-Onlyで動くのかはちょっと怪しい)
- canvas-confetti 🎉 に対応するため

Improve CSP

---

packages/backend/src/misc/id/aid.ts
packages/backend/src/server/api/endpoints/notes/timeline.ts

13.11.0 マージ時のミスを修正

---

packages/backend/src/GlobalModule.ts
packages/backend/src/core/AntennaService.ts
packages/backend/src/core/CacheService.ts
packages/backend/src/core/GlobalEventService.ts
packages/backend/src/core/MetaService.ts
packages/backend/src/core/RoleService.ts
packages/backend/src/core/WebhookService.ts
packages/backend/src/di-symbols.ts
packages/backend/src/server/api/StreamingApiServerService.ts

39cf80e19f10676b263004e0a1402fdc5a9613f9 を引っ張ってきた

fix(backend): イベント用redis分離が上手く動かない問題を修正

---

packages/backend/src/server/ServerService.ts

x-worker-host (https://github.com/MisskeyIO/misskey/pull/70) を復活させる
0e4fe59d57bc46cf0a18b2469d2c96772125bf88 で間違って消してしまっている

x-worker-host を復活させる

---

packages/backend/src/boot/common.ts
packages/backend/src/queue/QueueProcessorService.ts

QueueProcessorServiceのstartメソッドでqueue処理が開始されるように
なんか消えてた（13.12でもこうなってた）

fix(backend): restore start method in QueueProcessorService

---

packages/frontend/src/workers/test-webgl2.ts

OffscreenCanvas のフォールバックを機能させる
iOS <= 16.3 で読み込めるようにしたい

Fix offscreencanvas undefined

---

packages/backend/src/boot/common.ts

ServerStatsService を無効化

---

packages/backend/src/server/api/endpoints/get-online-users-count.ts
packages/backend/src/server/api/endpoints/hashtags/trend.ts
packages/frontend/src/pages/admin/overview.stats.vue
packages/frontend/src/widgets/WidgetOnlineUsers.vue
packages/frontend/src/widgets/WidgetTrends.vue

perf(backend): allow get for some endpoints

---

packages/backend/src/server/api/StreamingApiServerService.ts

JSON.parse の回数を削減する

---

packages/backend/package.json
packages/backend/src/core/AiService.ts
pnpm-lock.yaml

perf(backend): use mutex for nsfw model loading

---

packages/backend/src/core/QueueService.ts

外部サーバーへの配送が行われない問題を修正 (たぶん)

---

packages/backend/src/core/QueueService.ts

deliverMany に content の null チェックを追加

---

.config/example.yml
packages/backend/src/config.ts
packages/backend/src/core/SearchService.ts

MeilisearchにIndexするノートの範囲を設定できるように

feat: MeilisearchにIndexするノートの範囲を設定できるように

---

packages/backend/src/server/web/ClientServerService.ts

fix(backend): Use BullMQAdapter for bull-board

---

packages/frontend/src/components/MkPagination.vue
packages/frontend/src/nirax.ts

fix(frontend): scroll error

---

packages/frontend/src/components/MkPostForm.vue
packages/frontend/src/store.ts

feat: プレビューの表示状態を記憶するように

---

packages/backend/src/core/chart/core.ts
packages/backend/src/misc/prelude/array.ts
packages/backend/src/queue/processors/CleanRemoteFilesProcessorService.ts
packages/backend/src/queue/processors/DeleteAccountProcessorService.ts
packages/backend/src/queue/processors/DeleteDriveFilesProcessorService.ts
packages/backend/src/queue/processors/ExportBlockingProcessorService.ts
packages/backend/src/queue/processors/ExportFavoritesProcessorService.ts
packages/backend/src/queue/processors/ExportFollowingProcessorService.ts
packages/backend/src/queue/processors/ExportMutingProcessorService.ts
packages/backend/src/queue/processors/ExportNotesProcessorService.ts
packages/backend/src/server/ActivityPubServerService.ts
packages/backend/test/utils.ts
packages/frontend/src/components/MkDrive.vue
packages/frontend/src/components/MkMiniChart.vue
packages/frontend/src/components/MkPageWindow.vue
packages/frontend/src/components/MkPagination.vue
packages/frontend/src/scripts/array.ts
packages/frontend/src/widgets/server-metric/cpu-mem.vue
packages/frontend/src/widgets/server-metric/net.vue

This reverts commit 2b6dbd4fcbec380d65b0c318932d9eeb3fcb3f7b.
Node 18ではパフォーマンス問題がある
詳細は元のPRのコメントを参照

Revert "refactor: 可読性のため一部で`Array.prototype.at`を使うように"

---

packages/frontend/src/components/MkEmojiPicker.vue

feat: 絵文字の検索結果をもっと多めに表示するように

---

package.json

リリースのための作業です。
変更内容はバージョン番号の更新のみです。

Bump up version to 13.14.2-io

---

packages/frontend/src/components/MkPagination.vue
packages/frontend/src/nirax.ts
packages/frontend/src/pages/admin/abuses.vue
packages/frontend/src/pages/custom-emojis-manager.vue

Revert 11066

---

package.json

Bump up version to 13.14.2-io.1

---

gulpfile.mjs
packages/backend/src/server/web/views/base.pug
packages/backend/src/server/web/views/bios.pug
packages/backend/src/server/web/views/cli.pug
packages/backend/src/server/web/views/flush.pug

fix(deploy): 誤ったファイルがキャッシュされ新しいバージョンにアップデートされない問題の修正

---

package.json

Bump up version to 13.14.2-io.2

---

packages/backend/src/queue/processors/ReportAbuseProcessorService.ts

村上さんのところにずっと送られて迷惑だったのでいったん消して、あとでWebHookにする

fix: 通報の通知メールを発送しないように

---

packages/backend/src/queue/processors/ReportAbuseProcessorService.ts
packages/frontend/src/pages/admin/abuses.vue

fix: Productionビルドで通報の即時解決の一覧が見えない問題を修正

---

package.json

Bump up version to 13.14.2-io.3

---

packages/frontend/src/pages/emoji-edit-dialog.vue

spec: カスタム絵文字のライセンスの項目を複数行テキストに

---

packages/backend/src/server/api/endpoints/announcements.ts

fix: 非ログイン状態でお知らせの読み込みができない問題の修正

---

packages/backend/src/server/api/endpoints/admin/abuse-report-resolver/create.ts
packages/backend/src/server/api/endpoints/admin/abuse-report-resolver/update.ts
packages/frontend/src/components/MkAbuseReportResolver.vue
packages/frontend/src/pages/admin/abuses.vue

placeholderの追加
スタイルエラー修正
placeholderに関してはまだテストできていません（でもたぶん動くはず）

feat: 通報の即時解決機能の改善

---

package.json

Bump up version to 13.14.2-io.4

---

packages/frontend/src/pages/settings/2fa.vue

ioモデレーターチームの要請
始めて2FAのバックアップコードを見る人は１つのコードだと思うことがあるらしい

enhance(frontend): 2FAのバックアップコードに番号を付けて複数個だと分かりやすくする

---

packages/backend/src/core/CreateSystemUserService.ts
packages/backend/src/core/SignupService.ts

enhance(backend): use RSA 3072bit

---

packages/frontend/src/components/MkUrlPreview.vue
packages/frontend/src/components/MkUrlPreviewPopup.vue

devビルドでURLプレビューに失敗するURLを投稿してマウスホバー操作などをするとJSエラーでfrontendが固まるなどの問題があったので修正

fix: devビルドでURLプレビューに失敗した場合に起こる不具合を修正

---

packages/frontend/src/pages/instance-info.vue
packages/misskey-js/etc/misskey-js.api.md
packages/misskey-js/src/api.types.ts
packages/misskey-js/src/entities.ts

https://redirect.github.com/misskey-dev/misskey/pull/11429

fix(frontend, misskey-js): make block switch work

---

packages/backend/src/server/api/endpoints/notes/user-list-timeline.ts

https://redirect.github.com/misskey-dev/misskey/pull/11480

fix: muteがapiからのuser list timeline取得で機能しない

---

packages/frontend/src/components/MkNoteSub.vue

https://redirect.github.com/misskey-dev/misskey/pull/11711

fix: word mute is not applied to sub note

---

packages/backend/tsconfig.json
packages/frontend/tsconfig.json
packages/misskey-js/tsconfig.json
packages/sw/tsconfig.json

fix: 一部のタイプ定義を認識できない問題を修正

---

packages/backend/src/core/AnnouncementService.ts
packages/frontend/src/pages/admin/announcements.vue

enhance: ダイアログのお知らせをアーカイブした時イベントが発生しないように・アーカイブされたお知らせをわかりやすく

---

package.json

Bump up version to 13.14.2-io.5

---

package.json

Bump up version to 13.14.2-io.6

---

packages/backend/src/core/activitypub/models/ApPersonService.ts
packages/backend/src/server/api/endpoints/admin/queue/deliver-delayed.ts
packages/backend/src/server/api/endpoints/admin/queue/inbox-delayed.ts

deliver-delayed で URL のパースに失敗した際に全てがコケる問題を修正

---

packages/backend/package.json
pnpm-lock.yaml

update sharp to 0.32.6

---

package.json

Bump up version to 13.14.2-io.7

---

package.json

 Bump up version to 13.14.2-io.8

---

packages/backend/src/core/PollService.ts

https://redirect.github.com/misskey-dev/misskey/pull/11977

連合なしアンケートのUpdateがリモートに配信されてしまうのを修正

---

package.json

Bump up version to 13.14.2-io.9

---

package.json

Bump up version to 13.14.2-io.10

---

locales/index.d.ts
locales/ja-JP.yml
packages/frontend/src/components/MkInfo.vue
packages/frontend/src/components/MkPostForm.vue

投稿フォームにNSFWガイドラインへの導線を追加
NSFWガイドラインをより周知させるため

投稿フォームにNSFWガイドラインへの導線を追加

---

packages/frontend/src/components/MkDialog.vue
packages/frontend/src/os.ts
packages/frontend/src/pages/custom-emojis-manager.vue

絵文字のSet Lisenceを複数行対応

---

packages/backend/src/server/api/stream/channels/role-timeline.ts

ロールタイムラインで renote, reply を pack するように
たぶん https://github.com/misskey-dev/misskey/issues/11940

ロールタイムラインで renote, reply を pack するように

---

package.json

Bump up version to 13.14.2-io.11

---

packages/backend/src/core/NoteCreateService.ts

NotesStreamに流す新規ノートは匿名でpackするように

---

packages/backend/src/core/RoleService.ts
packages/backend/src/server/api/endpoints/admin/roles/assign.ts
packages/backend/src/server/api/endpoints/admin/roles/unassign.ts

有効期限だけを変更したい場合があるので、期限だけ更新できるように
エラーの場合はエラーもちゃんと返すようにした
io開発チームの要請

ロールのアサインAPIで有効期間が変わった場合は期限だけを更新するように

---

locales/index.d.ts
locales/ja-JP.yml
packages/backend/migration/1696323464251-user-list-membership.js
packages/backend/migration/1696373953614-meta-cache-settings.js
packages/backend/migration/1696807733453-userListUserId.js
packages/backend/migration/1696808725134-userListUserId-2.js
packages/backend/src/GlobalModule.ts
packages/backend/src/config.ts
packages/backend/src/core/AccountMoveService.ts
packages/backend/src/core/CoreModule.ts
packages/backend/src/core/FeaturedService.ts
packages/backend/src/core/NoteCreateService.ts
packages/backend/src/core/ReactionService.ts
packages/backend/src/core/RedisTimelineService.ts
packages/backend/src/core/UserListService.ts
packages/backend/src/di-symbols.ts
packages/backend/src/models/entities/Meta.ts
packages/backend/src/models/entities/UserListJoining.ts
packages/backend/src/server/api/endpoints/admin/meta.ts
packages/backend/src/server/api/endpoints/admin/update-meta.ts
packages/frontend/src/pages/admin/external-services.vue
packages/frontend/src/pages/admin/index.vue
packages/frontend/src/pages/admin/settings.vue
packages/frontend/src/router.ts

Push 型 TL の書き込み部分だけを持ってくる
書き込み部分のみを持ってきて様子見したい
結構適当に持ってきたので抜けている可能性アリ

TLをPush型にする（Write only)

---

package.json

Bump up version to 13.14.2-io.12

---

packages/backend/migration/1696807733453-userListUserId.js

5億年かかるマイグレを修正

---

package.json

Bump up version to 13.14.2-io.12b

---

.config/docker_example.yml
.devcontainer/devcontainer.yml
.devcontainer/docker-compose.yml
.dockerignore
.github/workflows/test-backend.yml
.github/workflows/test-frontend.yml
.gitignore
chart/templates/Deployment.yml
docker-compose.yml.example
packages/backend/src/core/FeaturedService.ts
packages/backend/test/docker-compose.yml

テストなどで参照してるredisをkeydbに置き換え
運営環境ではkeydbで動いてるため

テストなどにKeyDBを使うように

---

packages/frontend/src/emojilist.json

fix: 個人カードのemojiがバッテリーになっている (misskey-dev#12190)

---

packages/backend/package.json
packages/backend/src/core/WebAuthnService.ts
pnpm-lock.yaml

spec(deps): update @simplewebauthn/server to 8.3.5

---

package.json

Bump up version to 13.14.2-io.13

---

package.json

 Bump up version to 13.14.2-io.13a

---

packages/backend/src/server/web/ClientServerService.ts

cheery-picked from c9aeccb2ab260ceedc126e6e366da8cd13ece4b2

fix(backend): ジョブキュー管理画面の認証を回避できる問題を修正

---

packages/frontend/package.json
packages/frontend/src/components/MkUrlPreview.vue
packages/frontend/test/url-preview.test.ts
pnpm-lock.yaml

cheery-picked from 007ed5c9298ba6d7374dc913f65a5600ac88f331, 2896fc6cb4f6f35df4b0a0c22c9be55ad3c8e19a, cb80dff7df07e9ea9292365fe82fc7af09cc63c1

enhance(frontend): X (formally known as Twitter)

---

package.json

Bump up version to 13.14.2-io.14

---

packages/frontend/src/components/MkPageWindow.vue
packages/frontend/src/components/MkPullToRefresh.vue
packages/frontend/src/ui/universal.vue

cheery-picked from a656447aa58440e9a41fa39e1c5d6ff3d859b64e, 39f731804812d2e325c8b5c7c9077ff9c4835bc4
https://redirect.github.com/misskey-dev/misskey/pull/12177#issuecomment-1793252580

enhance(frontend): improve pull to refresh

---

package.json

 Bump up version to 13.14.2-io.14a

---

.github/workflows/docker-io.yml

Docker のビルドキャッシュに type=registry を使用するように
タグでビルドしているため、Actions のキャッシュが効かない

Docker のビルドキャッシュに type=registry を使用する

---

package.json

Bump up version to 13.14.2-io.14b

---

packages/frontend/src/components/MkNotifications.vue

fix(frontend/MkNotifications): 通知が複数回表示されてしまう問題を修正

---

package.json

 Bump up version to 13.14.2-io.14c

---

Dockerfile

Docker イメージビルド時、package.json をコピーする前に pnpm fetch するように
毎回ビルド前に package.json のバージョンを変更しており、キャッシュが効かないため

Docker イメージビルド時、package.json をコピーする前に pnpm fetch するように

---

packages/frontend/src/components/MkNotifications.vue
packages/frontend/src/ui/deck/antenna-column.vue
packages/frontend/src/ui/deck/channel-column.vue
packages/frontend/src/ui/deck/column.vue
packages/frontend/src/ui/deck/direct-column.vue
packages/frontend/src/ui/deck/list-column.vue
packages/frontend/src/ui/deck/mentions-column.vue
packages/frontend/src/ui/deck/notifications-column.vue
packages/frontend/src/ui/deck/role-timeline-column.vue
packages/frontend/src/ui/deck/tl-column.vue

https://redirect.github.com/misskey-dev/misskey/pull/12274

enhance(frontend): デッキのカラムからリロードできる機能を追加 (misskey-dev#12274)

---

packages/frontend/src/components/MkAnimBg.vue

シェーダーコンパイルに失敗した場合詳細なエラー内容を出力できるように
当該箇所のエラーに関する問い合わせ

enhance(frontend): シェーダーコンパイルに失敗した場合詳細なエラー内容を出力できるように

---

package.json

Bump up version to 13.14.2-io.14d

---

packages/frontend/src/components/MkUrlPreview.vue

enhance(frontend): URLプレビューのサムネイルを隠す機能のblur効果がはみ出てしまう問題を修正

---

package.json

Bump up version to 13.14.2-io.15

---

package.json

Bump up version to 13.14.2-io.15a

---

packages/frontend/src/components/MkUpdated.vue

enhance(frontend): アップデート情報のリンクを意味のあるものにする

---

packages/backend/migration/1700415938358-createdAt-default.js

fix migration

---

package.json

Bump up version to 2023.11.1-io.0

---

packages/backend/src/boot/entry.ts

fix startup

---

package.json

Bump up version to 2023.11.1-io.0a

---

packages/frontend/src/ui/deck/column.vue

fix(frontend/deck): コラムのリロードボタンが2個存在する問題を修正

---

packages/backend/src/core/RoleService.ts

fix(backend): ロールタイムラインのFTLが正しいRedisサーバーに保存されない問題を修正

---

package.json

 Bump up version to 2023.11.1-io.0b

---

packages/backend/src/core/QueryService.ts
packages/backend/src/server/api/endpoints/drive/files/attached-notes.ts
packages/backend/src/server/api/endpoints/hashtags/users.ts
packages/backend/src/server/api/endpoints/notes/mentions.ts
packages/backend/src/server/api/endpoints/notes/search-by-tag.ts

SQLでANYをやめる
なんのインデックスも適用されないため

enhance(backend): ANY()をやめる

---

package.json

Bump up version to 2023.11.1-io.0c

---

packages/frontend/src/pages/admin-user.vue

fix(frontend): リモートのユーザーにロールを設定できるように

---

packages/backend/src/server/api/endpoints/i/update.ts
packages/frontend/src/pages/admin/roles.editor.vue
packages/frontend/src/pages/admin/roles.vue

enhance(word-mute): ワードミュートの制限を文字数から設定項目数に

---

packages/backend/src/server/api/endpoints/admin/ad/list.ts
packages/frontend/src/pages/admin/ads.vue

https://redirect.github.com/misskey-dev/misskey/pull/12385

enhance(ad): 広告掲載ページにてfilterをわかりやすく (misskey-dev#12385)

---

package.json

 Bump up version to 2023.11.1-io.1

---

packages/frontend/src/pages/user/index.timeline.vue

enhance(frontend): ユーザープロフィールページのノートタブで常にチャンネルのノートが含まれるように

---

package.json

Bump up version to 2023.11.1-io.1a

---

packages/backend/src/server/api/endpoints/admin/meta.ts
packages/frontend/src/components/MkUrlPreview.vue
packages/frontend/test/url-preview.test.ts

Merge misskey-dev/develop

---

package.json

 Bump up version to 2023.11.1-io.1b

---

package.json

 Bump up version to 2023.11.1-io.1c

---

packages/frontend/src/scripts/nyaize.ts
packages/frontend/src/workers/test-webgl2.ts

iOS 16.4未満のSafariでRegExpのLookbehindをサポートしてなくて https://caniuse.com/js-regexp-lookbehind
`SyntaxError: Invalid regular expression: invalid group specifier name`エラーが発生し、エラー画面になる
まだ７％くらいのiOS 15ユーザーがいるらしい
https://iosref.com/ios-usage

enhance(frontend): ブラウザの互換性向上

---

packages/backend/src/server/api/EndpointsModule.ts
packages/backend/src/server/api/endpoints.ts
packages/backend/src/server/api/endpoints/users/stats.ts
packages/frontend/src/pages/settings/account-stats.vue
packages/frontend/src/pages/settings/other.vue
packages/frontend/src/router.ts
packages/misskey-js/etc/misskey-js.api.md
packages/misskey-js/src/api.types.ts

以前のバージョンから消えたユーザー統計表示機能の復活
ioだとインデックス2個作ったら爆速になったので復活させる

feature(backend): ユーザー統計表示機能の復活

---

package.json

 Bump up version to 2023.11.1-io.2

---

package.json

 Bump up version to 2023.11.1-io.2a

---

packages/backend/src/server/api/endpoints/notes/featured.ts

notes/featured で結果がなかった場合にエラーになる可能性がある問題を修正
https://github.com/misskey-dev/misskey/commit/986623dbdca61473fb4e60ff746c6c77e3a9d442

notes/featured で結果がなかった場合にエラーになる可能性がある問題を修正

---

package.json

Bump up version to 2023.11.1-io.3

---

package.json

 Bump up version to 2023.11.1-io.3a

---

packages/backend/src/server/api/endpoints/notes/conversation.ts
packages/backend/src/server/api/endpoints/notes/featured.ts
packages/backend/src/server/api/endpoints/notes/search.ts
packages/backend/src/server/api/endpoints/users/featured-notes.ts
packages/backend/src/server/api/endpoints/users/get-frequently-replied-users.ts
packages/backend/test/e2e/users.ts

enhance(backend): 検索・ハイライト機能でミュート・ブロックが適用されるように

---

packages/backend/src/core/NotePiningService.ts
packages/backend/src/server/ActivityPubServerService.ts

https://redirect.github.com/misskey-dev/misskey/pull/12541 を持ってきた
MisskeyIO#276

fix: Filter featured collection

---

packages/backend/src/server/api/endpoints/users/reactions.ts

適用前
```
Limit  (cost=1007.95..11520.40 rows=20 width=666) (actual time=11481.234..11483.669 rows=20 loops=1)
->  Nested Loop  (cost=1007.95..4221229.19 rows=8029 width=666) (actual time=11481.234..11483.666 rows=20 loops=1)
->  Gather Merge  (cost=1000.69..4124785.79 rows=10159 width=56) (actual time=11481.204..11483.446 rows=20 loops=1)
Workers Planned: 7
Workers Launched: 7
"              ->  Parallel Index Scan Backward using ""PK_767ec729b108799b587a3fcc9cf"" on note_reaction reaction  (cost=0.57..4122541.19 rows=1451 width=56) (actual time=83.020..10055.428 rows=134 loops=8)"
"                    Filter: ((""userId"")::text = '9dg16lig0m'::text)"
Rows Removed by Filter: 21873758
"        ->  Index Scan using ""PK_96d0c172a4fba276b1bbed43058"" on note  (cost=7.26..9.49 rows=1 …
```

enhance(backend): ユーザーのリアクションの一覧APIのパフォーマンスの改善

---

package.json

Bump up version to 2023.11.1-io.4

---

packages/backend/src/core/AnnouncementService.ts
packages/frontend/src/pages/admin/announcements.vue
packages/frontend/src/pages/announcements.vue

・過去のお知らせでは表示順設定を適用しないように
・過去のお知らせでもわかったボタンが出るように
・お知らせ管理画面では表示順設定を適用しないように
・お知らせ管理画面のページング処理のバグ修正

fix(announcement): お知らせ機能の改善・バグ修正

---

package.json

Bump up version to 2023.11.1-io.5a

---

packages/backend/src/misc/cache.ts

https://github.com/MisskeyIO/misskey/pull/174 の変更を RedisKVCache に反映した
同じ現象が RedisKVCache で起きているので

RedisKVCache で Redis から読み取った値を MemoryKVCache に書き戻す

---

package.json

Bump up version to 2023.11.1-io.5b

---

packages/backend/src/GlobalModule.ts
packages/backend/src/core/QueueModule.ts
packages/backend/src/daemons/QueueStatsService.ts
packages/backend/src/di-symbols.ts
packages/backend/src/queue/QueueProcessorService.ts
packages/backend/src/queue/const.ts

This reverts commit 7122657f13a871c6513e1b235859d32a1b9cfe11.
jobqueueのredisサーバーが応答なしになる問題が起きるため

Revert "enhance(backend): redisForJobQueue の接続を使い回す (MisskeyIO#268)"

---

packages/backend/src/core/EmailService.ts

deep-email-validatorを通ったメアドのみverifymail.ioで確認するように
verifymail.ioのリクエスト数を減らす・Basicプラン契約でもMXをチェックできるように

enhance(Email Validation): deep-email-validatorを通ったメアドのみverifymail.ioで確認するように

---

packages/backend/src/server/api/endpoints/meta.ts
packages/frontend/src/components/MkDateSeparatedList.vue
packages/frontend/src/components/global/MkAd.vue
packages/frontend/src/pages/admin/ads.vue
packages/frontend/src/pages/flash/flash.vue
packages/frontend/src/pages/gallery/post.vue
packages/frontend/src/pages/page.vue
packages/misskey-js/src/autogen/types.ts

`square`タイプの広告が全然表示されない問題を修正
APIにだけ存在していた`vertical`タイプの広告が設定できるように
io運営チーム要請

enhance(AD): 表示される広告の選定条件を変更、縦に長いタイプを設定できるように

---

package.json

Bump up version to 2023.12.2-io.1

---

packages/frontend/src/components/MkPostForm.vue

絵文字ピッカーを開くと入力ができなくなる問題を修正
修正漏れ

fix(MkPostForm): 絵文字ピッカーを開くと入力ができなくなる問題を修正

---

package.json

 Bump up version to 2023.12.2-io.1a

---

packages/backend/src/server/api/stream/channels/hybrid-timeline.ts

デバッグ用だと思われる console.log を削除
本番環境で流れてもログ量が増えるだけで無駄だと思うので

デバッグ用だと思われる console.log を削除

---

packages/backend/src/config.ts
packages/backend/src/core/QueueModule.ts
packages/backend/src/daemons/QueueStatsService.ts
packages/backend/src/queue/QueueProcessorService.ts
packages/backend/src/queue/const.ts

ジョブキューの設定の項目をキューごとに分ける
それぞれ違うサーバーに設定したいため

enhance(Queue): ジョブキューの設定の項目をキューごとに分ける

---

.github/workflows/docker-io.yml

ioブランチにpushされるたびにdockerビルドが走るようにする
beta用に毎回プレリリースを出すのはだるいため

chore(ci): ioブランチのコミットごとにdockerイメージをビルドするように

---

package.json

Bump up version to 2023.12.2-io.1b

---

package.json

Bump up version to 2023.12.2-io.1c

---

packages/backend/src/queue/QueueProcessorService.ts
packages/backend/src/queue/const.ts

lockDurationを2倍、stalledIntervalをlockのrenewalが2回失敗したタイミングまで延ばす
stallしまくる問題の回避

spec(Queue): lockDurationとstalledIntervalを増やす

---

.dockerignore
.gitmodules
packages/frontend/.storybook/changes.ts

使われてないassetsを消して、fluent-emojisはioのフォークを参照するようにした
本家のrepositoryを参照するのにリスクしかないので

chore(repository): 未使用のgitmodulesの削除、fluent-emojisのgitmodulesの参照をioのフォークに

---

package.json

Bump up version to 2023.12.2-io.1d

---

packages/backend/src/GlobalModule.ts
packages/backend/src/config.ts
packages/backend/src/core/QueueModule.ts
packages/backend/src/daemons/QueueStatsService.ts
packages/backend/src/queue/QueueProcessorService.ts
packages/backend/src/queue/const.ts

~~lockDurationを90秒・lockRenewTimeを10秒に~~
BullMQのQueue/Workerの詳細設定を設定ファイルから設定できるように
~~redisが不安定な場合、ロックが取れなくてジョブの完了処理ができない場合がある~~
設定ファイルで設定できたほうがよさそう

spec(Queue): BullMQのQueue/Workerの詳細設定を設定ファイルから設定できるように

---

package.json

Bump up version to 2023.12.2-io.1e

---

packages/backend/package.json
pnpm-lock.yaml

deps(backend): Upgrade BullMQ to 5.1.1

---

package.json

Bump up version to 2023.12.2-io.1f

---

package.json

Bump up version to 2023.12.2-io.1g

---

package.json

Bump up version to 2023.12.2-io.1h

---

package.json

Bump up version to 2023.12.2-io.1i

---

packages/backend/src/core/activitypub/ApInboxService.ts
packages/backend/src/core/activitypub/models/ApNoteService.ts
packages/backend/src/misc/status-error.ts
packages/backend/src/queue/processors/DeliverProcessorService.ts
packages/backend/src/queue/processors/InboxProcessorService.ts
packages/backend/src/queue/processors/WebhookDeliverProcessorService.ts

ActivityPub 周りで 429 を受け取った際にリトライするように
429 はリトライしたほうが良いとされている

ActivityPub 周りで 429 を受け取った際にリトライするように

---

package.json

Bump up version to 2023.12.2-io.1j

---

packages/frontend/src/filters/bytes.ts
packages/frontend/src/filters/kmg.ts
packages/frontend/src/widgets/WidgetJobQueue.vue

https://redirect.github.com/misskey-dev/misskey/pull/12896

enhance: Use SI prefixes for job queue widget, extends bytes (misskey-dev#12896)

---

packages/backend/src/core/QueueService.ts
packages/backend/src/core/activitypub/ApRequestService.ts
packages/backend/src/queue/processors/DeliverProcessorService.ts
packages/backend/src/queue/types.ts

https://redirect.github.com/misskey-dev/misskey/pull/12916

enhance(backend): ActivityPub Deliver queueでBodyを事前処理するように (misskey-dev#12916)

---

package.json

Bump up version to 2023.12.2-io.1k

---

packages/backend/src/core/HttpRequestService.ts

Bearcaps https://docs.joinmastodon.org/spec/bearcaps/ に対応
Mastodonの一部の機能でこのURLで送られてくるようになっているので
たぶんMastodonのサークル機能だとspecified投稿としてresolveされる
cc: @syuilo

feat(backend): Bearcaps URLに対応

---

packages/backend/src/core/activitypub/ApInboxService.ts

429の処理を修正
MisskeyIO#324 で修正したつもりが、await してなかったり、throw 忘れ？だったりで Bull にエラーが行ってなさそうだったので

fix(backend): 429 のハンドリングを修正

---

package.json

Bump up version to 2023.12.2-io.1l

---

packages/frontend/src/components/MkNote.vue

fix: ワードミュートに該当したノートを非表示にできるように

---

packages/backend/src/server/api/stream/channels/user-list.ts
packages/frontend/src/components/MkTimeline.vue

https://redirect.github.com/misskey-dev/misskey/pull/12932

fix: リストライムラインの「リノートを表示」が正しく機能しない問題を修正 (misskey-dev#12932)

---

packages/frontend/src/components/MkAutocomplete.vue
packages/frontend/src/components/MkEmojiPicker.vue

https://redirect.github.com/misskey-dev/misskey/pull/12928

enhance(frontend): 絵文字ピッカー/オートコンプリートで完全一致の絵文字を優先するように (misskey-dev#12928)

---

package.json

Bump up version to 2023.12.2-io.2

---

package.json

 Bump up version to 2023.12.2-io.2a

---

packages/backend/src/core/activitypub/models/ApNoteService.ts

MisskeyIO#340 のバグ修正
meta.blockedHostsを見てしまっていた

feat(federation): 特定の連合サーバーのメディアを全てセンシティブとして設定が効かない問題を修正

---

package.json

Bump up version to 2023.12.2-io.2b

---

packages/backend/src/boot/entry.ts

`uncaughtException`時同じエラーが2回出力されるのでconsoleの方を削除
見づらくなるので

chore(logging): エラーログが2回出力される問題を修正

---

packages/backend/src/boot/entry.ts
packages/backend/src/boot/master.ts
packages/backend/src/core/AiService.ts
packages/backend/src/core/DriveService.ts
packages/backend/src/core/EmailService.ts
packages/backend/src/core/FetchInstanceMetadataService.ts
packages/backend/src/core/NoteCreateService.ts
packages/backend/src/core/RemoteUserResolveService.ts
packages/backend/src/core/WebAuthnService.ts
packages/backend/src/core/activitypub/ApInboxService.ts
packages/backend/src/core/activitypub/models/ApNoteService.ts
packages/backend/src/core/activitypub/models/ApPersonService.ts
packages/backend/src/logger.ts
packages/backend/src/queue/QueueProcessorService.ts
packages/backend/src/queue/processors/ExportCustomEmojisProcessorService.ts
packages/backend/src/server/FileServerService.ts
packages/backend/src/server/api/ApiCallService.ts
packages/backend/src/server/api/endpoints/drive/files/create.ts
packages/backend/src/server/oauth/OAuth2ProviderService.ts
packages/backend/src/server/web/ClientServerService.ts
packages/backend/test/unit/FileInfoService.ts

無秩序にconsole.errorに出力されるエラー情報などをloggerにまとめる
エラーのフィールドの名前を「error」に一貫化
エラーのコンテキストが比較的分かるように
デバッグを用意にするため

enhance(logging): ログの情報を増やす

---

package.json

Bump up version to 2023.12.2-io.2d

---

package.json

Bump up version to 2023.12.2-io.2e

---

packages/backend/src/daemons/QueueStatsService.ts

QueueStatsServiceの更新インタバルを増やす
パフォーマンスの改善のため（本当はすごい廃止にしたい）

spec(QueueStatsService): Increase update interval

---

packages/backend/src/boot/entry.ts
packages/backend/src/logger.ts
packages/backend/src/server/api/endpoints/admin/emoji/copy.ts
packages/backend/src/server/api/endpoints/drive/files/create.ts

エラー時もっと詳しい情報が残るように
`JSON.stringify`だと`Error`タイプのstringifyの結果が`{}`としかならないので何の役にも立たないことがある

enhance(logging): エラー時もっと詳しい情報が残るように

---

CHANGELOG.md
locales/index.d.ts
locales/ja-JP.yml
packages/backend/migration/1705222772858-optimize-note-index-for-array-column.js
packages/backend/src/models/Note.ts
packages/backend/src/server/FileServerService.ts
packages/backend/test/e2e/drive.ts
packages/backend/test/utils.ts
packages/frontend/src/components/MkMediaAudio.vue
packages/frontend/src/components/MkMediaBanner.vue
packages/frontend/src/components/MkMediaRange.vue
packages/frontend/src/components/MkMediaVideo.vue
packages/frontend/src/filters/hms.ts
packages/frontend/src/global/router/definition.ts
packages/frontend/src/navbar.ts
packages/frontend/src/pages/games.vue
packages/frontend/src/scripts/device-kind.ts
packages/frontend/src/ui/_common_/common.ts

Merge upstream

---

package.json

Bump up version to 2023.12.2-io.2f

---

packages/backend/package.json
packages/backend/src/core/LoggerService.ts
packages/backend/src/logger.ts
packages/backend/src/postgres.ts
pnpm-lock.yaml

`@/logger.ts`の中身を`pino`に置き換える
`console.log`と`node:util.inspect`だとjsonの構造化ログにどうしても向いてなかったので

enhance(logging): ログの処理をpinoに置き換える

---

package.json

Bump up version to 2023.12.2-io.2g

---

packages/backend/src/core/NoteCreateService.ts

fix: MisskeyIO#365 にもかかわらずまだ通知が発生する場合がある問題を修正

---

package.json

Bump up version to 2023.12.2-io.2h

---

packages/frontend/src/pizzax.ts

fix(pizzax): オブジェクトタイプのみdefaultsDeepが適用されるように

---

package.json
packages/misskey-js/package.json

Bump up version to 2024.1.0-io.1a

---

package.json
packages/misskey-js/package.json

Bump up version to 2024.1.0-io.1b

---

package.json
packages/misskey-js/package.json

Bump up version to 2024.1.0-io.1c

---

package.json
packages/misskey-js/package.json

Bump up version to 2024.1.0-io.1d

---

package.json
packages/misskey-js/package.json

Bump up version to 2024.1.0-io.1e

---

package.json
packages/misskey-js/package.json

Bump up version to 2024.1.0-io.1f

---

package.json
packages/misskey-js/package.json

Bump up version to 2024.1.0-io.1g

---

package.json
packages/misskey-js/package.json

Bump up version to 2024.1.0-io.1h

---

packages/backend/src/server/api/endpoints/admin/emoji/list.ts

fix(backend/admin/emoji/list): 検索が正常に動作しない問題を修正

---

package.json
packages/misskey-js/package.json

Bump up version to 2024.1.0-io.1i

---

packages/backend/src/server/oauth/OAuth2ProviderService.ts

fix(backend): OAuth2認証ができない問題を修正

---

package.json
packages/misskey-js/package.json
packages/misskey-js/src/autogen/apiClientJSDoc.ts
packages/misskey-js/src/autogen/endpoint.ts
packages/misskey-js/src/autogen/entities.ts
packages/misskey-js/src/autogen/models.ts
packages/misskey-js/src/autogen/types.ts

Bump up version to 2024.2.0-io.1

---

packages/frontend/src/components/MkPostFormAttaches.vue

fix(frontend): 投稿フォームのセンシティブとして設定メニューのアイコンが間違っていたのを修正

---

package.json
packages/misskey-js/package.json

Bump up version to 2024.2.0-io.1a

---

package.json
packages/misskey-js/package.json

Bump up version to 2024.2.0-io.1b

---

package.json
packages/misskey-js/package.json

Bump up version to 2024.2.0-io.1c

---

packages/backend/src/config.ts
packages/backend/src/postgres.ts

spec(backend): データベースのキャッシュにRedisの代わりにin-memoryキャッシュを使用する

---

package.json
packages/misskey-js/package.json

Bump up version to 2024.2.0-io.1d

---

packages/frontend/package.json
pnpm-lock.yaml

deps(frontend): Downgrade Vue to 3.4.15

---

package.json
packages/misskey-js/package.json

Bump up version to 2024.2.0-io.1e

---

package.json
packages/misskey-js/package.json

Bump up version to 2024.2.0-io.1f

---

packages/backend/src/core/EmailService.ts

verifymail.io のレスポンスをキャッシュする

---

packages/backend/src/logger.ts

spec(backend): severityのラベルをJSON形式のログに追加

---

package.json
packages/misskey-js/package.json

Bump up version to 2024.2.0-io.1g

---

package.json
packages/misskey-js/package.json

Bump up version to 2024.2.0-io.1h

---

packages/backend/src/core/EmailService.ts

ドメイン単位にしたことにより捨てアドチェックが壊れていた問題を修正

---

package.json
packages/misskey-js/package.json

Bump up version to 2024.2.0-io.1i

---

packages/backend/src/logger.ts

chore(logging): `severity`フィールドがログに出てくる問題を修正

---

.github/workflows/test-frontend.yml
cypress/e2e/basic.cy.js
cypress/e2e/router.cy.js

cypressのテストの失敗時、永遠に止まらない問題を回避
失敗しないようタイムアウトの延長・15分で止まるように

ci(test-frontend): cypressのテストの失敗時、永遠に止まらない問題を回避

---

package.json
packages/misskey-js/package.json

Bump up version to 2024.2.0-io.1j

---

packages/backend/src/server/ServerService.ts
packages/backend/src/server/oauth/OAuth2ProviderService.ts

spec(OAuth2): `/oauth/userinfo`と`/oauth/token/introspect`を実装

---

packages/backend/src/postgres.ts

クエリーのキャッシュ設定が期待通りの実装ではなかった問題を修正
In-Memory実装になるものだと思ってたらDBベースのキャッシュ実装になっていた

fix(backend): クエリーのキャッシュ設定が期待通りの実装ではなかった問題を修正

---

packages/backend/src/core/NoteCreateService.ts

spec(backend): リモートの投稿にも禁止ワードを適用

---

packages/backend/test/e2e/note.ts
packages/backend/test/unit/activitypub.ts

fix(backend/test): MisskeyIO#437 によりテストが失敗する問題を修正

---

package.json
packages/misskey-js/package.json

Bump up version to 2024.2.0-io.1k

---

packages/frontend/src/pages/about.vue

spec(frontend): aboutページのUI調整

---

packages/backend/src/models/Meta.ts

fix(models): `disableRegistration`のデフォルト値が更新されていなかったので

---

packages/backend/src/models/Meta.ts

Revert "fix(models): `disableRegistration`のデフォルト値が更新されていなかったので"

---

package.json
packages/misskey-js/package.json

Bump up version to 2024.2.0-io.1l

---

packages/backend/src/core/NoteCreateService.ts

enhance(NoteCreateService): センシティブワード・禁止ワード設定に関するログを追加

---

CHANGELOG.md
packages/backend/src/core/CacheService.ts
packages/backend/src/core/activitypub/ApDbResolverService.ts
packages/backend/src/core/activitypub/ApInboxService.ts

Cherry-picked from 1150a1a8729a71e295ee30d69b158b6e89fbd48a
Cherry-picked from b824615a6b1ea675c5825d61d742c534ef42f9dc
Cherry-picked from 4e6cf78e29472966f10bf5c9b40aa4ab9242f991
https://redirect.github.com/misskey-dev/misskey/pull/13275

リモートユーザーが復活してもキャッシュにより該当ユーザーのActivityが受け入れられないのを修正 (misskey-dev#13275)

---

package.json
packages/misskey-js/package.json

Bump up version to 2024.2.0-io.1m

---

packages/misskey-js/src/autogen/types.ts

fix(misskey-js): `notifications/create`のレスポンスの型の更新

---

packages/backend/src/logger.ts
packages/backend/src/server/api/SigninApiService.ts
packages/backend/src/server/api/SignupApiService.ts
packages/backend/src/server/api/endpoints/federation/instances.ts
packages/backend/src/server/api/endpoints/notes/create.ts

spec(backend): 一部のエンドポイントにログを追加

---

package.json
packages/misskey-js/package.json

Bump up version to 2024.2.0-io.2

---

packages/backend/src/core/HttpRequestService.ts
packages/backend/src/core/activitypub/ApRequestService.ts
packages/backend/src/core/activitypub/ApResolverService.ts
packages/backend/src/core/activitypub/LdSignatureService.ts
packages/backend/src/core/activitypub/misc/validator.ts
packages/backend/test/e2e/fetch-validate-ap-deny.ts
packages/backend/test/unit/activitypub.ts
packages/backend/test/utils.ts

hotfix(backend): GHSA-qqrm-9grj-6v32

---

package.json
packages/misskey-js/package.json

Bump up version to 2024.2.0-io.2a

---

packages/backend/src/core/DriveService.ts
packages/backend/src/core/NoteCreateService.ts
packages/backend/src/core/ReactionService.ts
packages/backend/src/core/UserAuthService.ts
packages/backend/src/core/UserFollowingService.ts
packages/backend/src/core/WebAuthnService.ts
packages/backend/src/misc/identifiable-error.ts
packages/backend/src/server/api/ApiCallService.ts
packages/backend/src/server/api/error.ts

spec(backend): IdentifiableErrorの場合もエラーメッセージが正常に表示されるように

---

package.json
packages/misskey-js/package.json

Bump up version to 2024.2.0-io.2b

---

packages/backend/src/server/oauth/OAuth2ProviderService.ts

fix(backend/oauth/api/userinfo): `updated_at`の実装が間違っている問題を修正

---

packages/backend/src/core/NoteCreateService.ts

Cherry-picked from 882924fe26d961c6ef5d7363b65855a380ff9371

spec(backend/NoteCreateService): ローカルユーザーがまだ誰もフォローしていないリモートユーザーによる投稿のフィルターの条件の調整

---

package.json
packages/misskey-js/package.json

Bump up version to 2024.2.0-io.2c

---

package.json
packages/misskey-js/package.json

Bump up version to 2024.2.0-io.2d

---

packages/backend/src/server/api/endpoints/drive/files/create.ts
packages/backend/src/server/api/endpoints/drive/files/upload-from-url.ts
packages/backend/test/e2e/drive.ts
packages/backend/test/e2e/endpoints.ts

spec(backend/drive/files): ネットワーク不安定・高負荷時ファイルが重複してアップロードされる問題を修正

---

packages/frontend/src/os.ts
packages/frontend/src/pages/settings/preferences-backups.vue

バックアップ名が null のバックアップが作成でき削除などの操作ができなくなる問題を修正

---

package.json
packages/misskey-js/package.json

Bump up version to 2024.2.0-io.2f

---

package.json
packages/misskey-js/package.json

Bump up version to 2024.2.0-io.2g

---

package.json
packages/misskey-js/package.json

Bump up version to 2024.2.0-io.2h

---

package.json
packages/misskey-js/package.json

Bump up version to 2024.2.0-io.2i

---

packages/frontend/src/components/MkEmojiPicker.vue

fix(frontend): MkEmojiPickerでカスタム絵文字が正常に表示されない問題を修正

---

package.json
packages/misskey-js/package.json

Bump up version to 2024.2.0-io.2j

---

.gitignore

https://connortumbleson.com/2024/02/26/the-disappointing-tea-xyz/

BAN Cryptocurrency Spam

---

packages/frontend/src/components/MkMediaAudio.vue
packages/frontend/src/components/MkMediaBanner.vue
packages/frontend/src/components/MkMediaImage.vue
packages/frontend/src/components/MkMediaVideo.vue
packages/frontend/src/components/MkNote.vue
packages/frontend/src/pages/user/index.files.vue
packages/frontend/src/pages/welcome.timeline.vue

spec(frontend): 非ログイン状態ではセンシティブに設定されたコンテンツを閲覧できないように

---

locales/en-US.yml
locales/index.d.ts
locales/ja-JP.yml
packages/backend/src/core/AntennaService.ts
packages/backend/src/core/RoleService.ts
packages/backend/src/models/json-schema/role.ts
packages/frontend/src/const.ts
packages/frontend/src/pages/admin/roles.editor.vue
packages/frontend/src/pages/admin/roles.vue
packages/misskey-js/src/autogen/types.ts

feat: アンテナに保持するノート数をポリシーに追加

---

locales/en-US.yml
locales/index.d.ts
locales/ja-JP.yml
packages/backend/src/core/DriveService.ts
packages/backend/src/core/RoleService.ts
packages/backend/src/models/json-schema/role.ts
packages/frontend/src/const.ts
packages/frontend/src/pages/admin/roles.editor.vue
packages/frontend/src/pages/admin/roles.vue
packages/misskey-js/src/autogen/types.ts

feat: AIによるNSFW検出を無視できるポリシーを追加

---

package.json
packages/misskey-js/package.json

Bump up version to 2024.3.0-io.0

---

packages/backend/src/logger.ts

fix(logging): pino-prettyの使用時のメモリ使用量の問題を修正

---

packages/frontend/src/components/MkNotifications.vue

fix(frontend): 通知が重複して受信される問題を修正

---

packages/frontend/src/components/MkMediaImage.vue

fix(frontend): 非ログイン状態でもaタグに画像のURLがリンクされている問題を修正

---

package.json
packages/misskey-js/package.json

Bump up version to 2024.3.1-io.0

---

package.json
packages/misskey-js/package.json

Bump up version to 2024.3.1-io.1a

---

package.json
packages/misskey-js/package.json

Bump up version to 2024.3.1-io.1b

---

packages/backend/src/server/web/ClientServerService.ts

`/_info_card_` から使用していないクエリを削除
使っていない上にそこそこ重いので
24ef4d3da2ffbb914931f5e173d6b3ebe21b0311 で使わなくなってそのままでした

/_info_card_ から使用していないクエリを削除

---

packages/backend/src/core/AntennaService.ts

アンテナに保持する最大ノート数の設定が機能していない問題を修正

---

package.json
packages/misskey-js/package.json

Bump up version to 2024.3.1-io.1c

---

packages/frontend/src/components/MkAutocomplete.vue
packages/frontend/src/scripts/autocomplete.ts

https://redirect.github.com/misskey-dev/misskey/pull/13384

Complete unicode emoji after last colon (misskey-dev#13384)

---

packages/backend/src/queue/processors/DeleteAccountProcessorService.ts

cheery-picked from tanukey-dev/tanukey@7ddecf1eab341952f75730f445445a9c15e8cfa0

fix(queue): アカウント削除が終わらない問題を修正

---

packages/backend/src/server/api/endpoints/notes/search-by-tag.ts
packages/frontend/src/pages/tag.vue
packages/misskey-js/src/autogen/types.ts

cheery-picked from TeamNijimiss/misskey@4fe36c8eb92435cc2f865e0224535432fd9b4eca

enhance: タグ検索においてローカルのみやファイル付きを指定できるように

---

packages/backend/src/server/web/views/note.pug
packages/backend/src/server/web/views/user.pug

enhance(OGP): ユーザーやノートのOGPでローカルとリモートユーザーの見分けが付かない問題を修正

---

packages/backend/src/server/sso/JWTIdentifyProviderService.ts

fix(SSO/JWT): JWTのヘッダーに`typ`を追加、serviceurlパラメータに対応

---

packages/frontend/src/components/MkPostForm.vue

fix(frontend/MkPostForm): 何らかの理由でファイルのアップロード・選択に失敗したゴミデータが残り投稿できなくなる問題を修正

---

.github/workflows/docker-beta.yml

spec(ci): beta ブランチ向けのGitHub Actions Workflowを追加

---

package.json
packages/misskey-js/package.json

Bump up version to 2024.3.1-io.2

---

package.json
packages/misskey-js/package.json

Bump up version to 2024.3.1-host.2

---

.github/workflows/docker-beta.yml
.github/workflows/docker-host.yml

fix(ci): タグ作成時のworkflowの整備

---

packages/backend/src/server/api/ApiCallService.ts
packages/backend/src/server/api/endpoint-base.ts
packages/backend/src/server/api/endpoints/admin/emoji/copy.ts
packages/backend/src/server/api/endpoints/drive/files/create.ts
packages/backend/src/server/api/error.ts
packages/frontend/src/components/MkDialog.vue
packages/frontend/src/os.ts

enhance(frontend): エラー発生時のダイアログに詳細情報を載せる

---

packages/backend/src/misc/normalize-email-address.ts
packages/backend/src/server/sso/JWTIdentifyProviderService.ts
packages/backend/src/server/sso/SAMLIdentifyProviderService.ts

fix(SSO): メールアドレスからコメント・タグを除外

---

package.json
packages/misskey-js/package.json

Bump up version to 2024.3.1-io.2b

---

packages/backend/src/server/sso/JWTIdentifyProviderService.ts
packages/backend/src/server/sso/SAMLIdentifyProviderService.ts

enhance(SSO): Attributeの調整

---

packages/frontend/src/scripts/sound.ts

fix(frontend): 同じ音源は短時間で重複して流れないように

---

packages/frontend/src/pages/admin-user.vue

fix(frontend): 管理用のユーザー詳細ページのコピーボタンのデータが期待と違う問題を修正

---

package.json
packages/misskey-js/package.json

Bump up version to 2024.3.1-io.2c

---

README.md
packages/frontend/src/components/MkVisitorDashboard.vue
packages/frontend/src/pages/about.vue

misc: misskeyusercontent.com → misskeyusercontent.jp

---

locales/en-US.yml
locales/ja-JP.yml
locales/ko-KR.yml
packages/frontend/src/scripts/warning-external-website.ts

enhance(frontend): 外部サイトへのリンクは移動の警告の条件の調整

---

package.json
packages/misskey-js/package.json

Bump up version to 2024.3.1-io.3

---

packages/backend/src/core/HashtagService.ts

enhance(backend): ハッシュタグのランキングをローカルユーザーに限定する

---

packages/frontend/src/pages/user/home.vue

spec(frontend): Skeb募集状態のユーザーページのリンクに外部リンクの表示を追加

---

package.json
packages/misskey-js/package.json

Bump up version to 2024.3.1-io.4

---

packages/backend/src/server/api/endpoints/users/get-following-birthday-users.ts

fix(backend): 年越しの時期で誕生日検索クエリーが誤動作する問題を修正

---

package.json
packages/misskey-js/package.json

Bump up version to 2024.3.1-io.4a

---

packages/backend/src/core/DeleteAccountService.ts
packages/backend/src/core/FetchInstanceMetadataService.ts
packages/backend/src/core/SignupService.ts

fix(backend): アカウントの作成と削除の途中でリトライが発生しても無視するように

---

packages/backend/src/server/api/endpoints/admin/accounts/delete.ts
packages/frontend/src/pages/admin-user.vue
packages/misskey-js/src/autogen/types.ts

enhance(moderation): 管理者がアカウントの物理削除・論理削除を選べるように

---

packages/frontend/src/widgets/WidgetBirthdayFollowings.vue

fix(frontend/WidgetBirthdayFollowings): ユーザーの名前が長いと投稿ボタンがはみ出てしまう問題を修正

---

package.json
packages/misskey-js/package.json

Bump up version to 2024.3.1-io.4b

---

packages/frontend/src/components/MkAutocomplete.vue
packages/frontend/src/scripts/search-emoji.ts

cheery-picked from anatawa12/misskey@47c4a6ed79451c9a9b60bf324568090d11dd0968
* fix code quality issues

chore: do not use fuzzy match for emojiComplete (misskey-dev#13384)

---

packages/backend/src/server/api/endpoints/users/get-following-birthday-users.ts

fix(backend/get-following-birthday-users): 一部の月でbirthdayのタイムスタンプが1ヶ月ズレる問題を修正

---

packages/frontend/src/pages/user/home.vue

fix(frontend): Skebのリクエストを募集中ならクリエイターの表示になるように

---

package.json
packages/misskey-js/package.json

Bump up version to 2024.3.1-io.4c

---

packages/backend/src/@types/ioredis.d.ts
packages/backend/src/GlobalModule.ts
packages/backend/src/server/api/endpoints/drive/files/create.ts
packages/backend/src/server/api/endpoints/drive/files/upload-from-url.ts
packages/backend/src/server/api/endpoints/notes/create.ts

fix(backend): 処理に失敗するとidempotentキーを削除してしまいその後のリクエストが通ってしまう問題を修正

---

packages/frontend/src/components/MkRoleBadgeIcon.vue

fix(skeb/role): Skebロールのバッジをクリックできることをわかるようにカーソルを変更

---

package.json
packages/misskey-js/package.json

Bump up version to 2024.3.1-io.5

---

package.json
packages/misskey-js/package.json

Bump up version to 2024.3.1-io.5b

---

package.json
packages/misskey-js/package.json

Bump up version to 2024.3.1-io.5c

---

packages/backend/src/server/oauth/OAuth2ProviderService.ts
packages/backend/src/server/sso/JWTIdentifyProviderService.ts
packages/backend/src/server/sso/SAMLIdentifyProviderService.ts

spec(SSO): メールアドレスが登録されていない場合、メアドフィールドの値にaactを入れる

---

package.json
packages/misskey-js/package.json

Bump up version to 2024.3.1-io.6

---

locales/index.d.ts
locales/ja-JP.yml
packages/backend/src/models/Webhook.ts
packages/backend/src/queue/processors/ReportAbuseProcessorService.ts
packages/backend/src/server/api/endpoints/admin/resolve-abuse-user-report.ts
packages/backend/src/server/api/endpoints/i/webhooks/create.ts
packages/backend/src/server/api/endpoints/i/webhooks/update.ts
packages/backend/src/server/api/endpoints/users/report-abuse.ts
packages/frontend/src/pages/settings/webhook.edit.vue
packages/frontend/src/pages/settings/webhook.new.vue

通報が登録された、解決した、自動解決されたことをWebhookで通知できるようにする。
モデレーション効率向上

feat(webhook): 通報の登録、解決、自動解決に対応

---

locales/en-US.yml
locales/ko-KR.yml

i18n: MisskeyIO#615

---

packages/backend/src/core/NoteCreateService.ts
packages/backend/src/misc/is-renote.ts
packages/backend/src/server/api/stream/channels/global-timeline.ts
packages/backend/src/server/api/stream/channels/home-timeline.ts
packages/backend/src/server/api/stream/channels/hybrid-timeline.ts
packages/backend/src/server/api/stream/channels/local-timeline.ts
packages/backend/src/server/api/stream/channels/role-timeline.ts
packages/backend/src/server/api/stream/channels/user-list.ts

fix(backend): リノートの評価の順番を変更、isQuote・isQuotePackedの挙動を修正

---

package.json
packages/misskey-js/package.json

Bump up version to 2024.3.1-io.7

---

locales/index.d.ts
packages/frontend/src/components/MkNewPassword.vue
packages/frontend/src/components/MkSignupDialog.form.vue
packages/frontend/src/pages/reset-password.vue
packages/frontend/src/pages/settings/security.vue

enhance(frontend): パスワード変更時にHIBPで流出パスワードをチェックするように

---

packages/backend/src/core/activitypub/ApRendererService.ts
packages/backend/src/core/activitypub/LdSignatureService.ts
packages/backend/src/core/activitypub/misc/contexts.ts
packages/backend/src/queue/processors/InboxProcessorService.ts

https://gist.github.com/tesaguri/f3c73f81bc000f669fc8adfab316603b

Hotfix GHSA-2vxv-pv3m-3wvj

---

packages/frontend/src/components/MkUrlPreview.vue

enhance(frontend): センシティブとして設定されたURLのプレビューサムネイルのblur調整

---

packages/backend/src/core/NoteCreateService.ts

センシティブワードの検出を投票の選択肢に対しても行うようにした。

enhance(backend): 投票の選択肢に対してもセンシティブワード検出を行うように

---

package.json
packages/misskey-js/package.json

Bump up version to 2024.5.0-io.1

---

packages/frontend/src/components/MkAbuseReport.vue
packages/frontend/src/pages/about.vue

chore(frontend): CSSのwarning解消、i18n

---

packages/backend/src/queue/processors/ReportAbuseProcessorService.ts
packages/backend/src/server/api/endpoints/admin/resolve-abuse-user-report.ts
packages/backend/src/server/api/endpoints/users/report-abuse.ts

enhance(backend): MisskeyIO#615 のパフォーマンス改善

---

packages/backend/src/core/MfmService.ts

MfmService.toHtml を JSDOM に戻す
happy-dom が VMContext を作っていて重い説がある

MfmService.toHtml を JSDOM に戻す

---

package.json
packages/misskey-js/package.json

Bump up version to 2024.5.0-io.1a

---

.github/workflows/dockle.yml

Update dockle to v0.4.14

---

packages/backend/src/core/entities/UserEntityService.ts
packages/backend/test/e2e/users.ts

一般ユーザーから見たユーザーのバッジの一覧に公開されていないものまで含まれていたため修正

公開バッジのみをpackするように

---

packages/backend/src/core/chart/charts/per-user-pv.ts
packages/backend/src/core/chart/core.ts
packages/backend/src/server/api/endpoints/users.ts
packages/misskey-js/src/autogen/types.ts

見つけるからUserを探す際に必要なAPIを先に追加
ローカルでテストしたけどユーザー数が少ないので一旦PR
良さそうであれば別PRで`見つける`のソートを変更します

api/usersに+pv -pvを追加

---

locales/zh-TW.yml

Add missing key (_timelines.media)

---

packages/backend/src/server/api/endpoints/roles/users.ts
packages/backend/src/server/api/endpoints/users/get-frequently-replied-users.ts

いくつかのエンドポイントで凍結済みのユーザーが居た場合のエラーを修正

---

packages/frontend/src/components/MkUserSetupDialog.Follow.vue
packages/frontend/src/pages/explore.users.vue

下記のフロントエンド修正
https://github.com/MisskeyIO/misskey/pull/653

PVを見て人気のユーザーを取得するように（ローカルのみ）

---

packages/frontend/src/components/MkNoteDetailed.vue

#660 でMkNoteDetailed.vueに変更を加え忘れていたのを修正しました。

fix(reaction): MkNoteDetailed.vueに変更を加え忘れていたのを修正

---

packages/frontend/src/pages/search.user.vue

ユーザー検索結果欄で無限にループする問題を解決

---

packages/frontend/src/components/MkNote.vue
packages/frontend/src/components/MkNoteDetailed.vue

ロールでリアクションを管理できるようにしたときに未ログインの時を考慮してなかったのを修正

Fix: 未ログインだとハートマークになってしまうのを修正

---

packages/frontend/src/components/MkReactionsViewer.details.vue
packages/frontend/vite.config.local-dev.ts

絵文字関連の不具合を修正

---

packages/backend/src/core/NoteCreateService.ts

ダイレクト投稿をユーザーごとのチャートから除外

---

packages/backend/src/server/api/endpoints/following/create.ts
packages/backend/src/server/api/endpoints/notes/create.ts
packages/misskey-js/src/autogen/types.ts

BotからBotのフォロー・リプライができないように

---

packages/backend/src/server/api/endpoints/drive/files/attached-notes.ts
packages/frontend/src/pages/admin-file.vue

enhance(moderation): モデレーターがファイルが添付されているノートを照会できるように

---

packages/frontend/src/pages/admin-user.vue

fix(moderation): MisskeyIO#656

---

locales/index.d.ts
locales/ja-JP.yml
packages/frontend/src/components/MkTutorialDialog.vue
packages/frontend/src/components/MkUserSetupDialog.Profile.vue
packages/frontend/src/components/MkUserSetupDialog.vue

チュートリアルが特定の操作を行うとスキップできてしまうのを修正。

チュートリアルが特定の操作でスキップできてしまうのを修正

---

locales/en-US.yml
locales/index.d.ts
locales/ja-JP.yml
locales/ja-KS.yml
locales/ko-KR.yml
packages/frontend/src/components/MkModalWindow.vue
packages/frontend/src/components/MkTutorialDialog.vue
packages/frontend/src/components/MkUserSetupDialog.vue

spec(frontend): チュートリアルにBotの設定を追加、チュートリアルをスキップ不可に

---

packages/backend/src/core/UserSuspendService.ts

fix(moderation): ユーザーが凍結された際、処理されていないフォローリクエストをすべて削除する

---

packages/backend/src/core/NoteCreateService.ts
packages/backend/src/core/ReactionService.ts

fix(backend): 一部policyがリモートユーザーに適用されない問題を修正

---

package.json
packages/backend/src/core/NoteCreateService.ts
packages/backend/src/core/ReactionService.ts
packages/backend/src/core/UserSuspendService.ts
packages/misskey-js/package.json

2024.5.0-host.2a

---

packages/backend/src/models/UserProfile.ts
packages/backend/src/models/json-schema/user.ts
packages/backend/src/server/api/endpoints/i/update.ts
packages/frontend/src/pages/settings/profile.vue
packages/frontend/src/pages/user/home.vue
packages/misskey-js/src/autogen/types.ts

spec(profile): 相互リンクバナーのサイズ変更・ID付与

---

package.json
packages/misskey-js/package.json

Bump up version to 2024.5.0-io.2b

---

package.json
packages/backend/src/models/UserProfile.ts
packages/backend/src/models/json-schema/user.ts
packages/backend/src/server/api/endpoints/i/update.ts
packages/frontend/src/pages/settings/profile.vue
packages/frontend/src/pages/user/home.vue
packages/misskey-js/package.json
packages/misskey-js/src/autogen/types.ts

2024.5.0-host.2b

---

locales/en-US.yml
locales/index.d.ts
locales/ja-JP.yml
locales/ko-KR.yml
packages/backend/src/core/RoleService.ts
packages/backend/src/core/entities/UserEntityService.ts
packages/backend/src/server/api/endpoints/i/update.ts
packages/frontend/src/pages/about.vue
packages/frontend/src/pages/admin/roles.editor.vue
packages/frontend/src/pages/settings/profile.vue
packages/frontend/src/pages/user/home.vue

spec(profile): 相互リンク機能のロールによる制御の仕様変更

---

packages/backend/src/models/UserProfile.ts
packages/backend/src/models/json-schema/user.ts
packages/backend/src/types.ts
packages/misskey-js/src/autogen/types.ts

spec(profile): 相互リンクの型定義の修正

---

packages/backend/src/core/activitypub/ApRendererService.ts

相互リンク機能を連合するようにしました。
resolve #702
io側アカウントの設定例
リモートでの表示例

enhance(federation/profile): 相互リンクのテキストが連合するように

---

locales/index.d.ts
locales/ja-JP.yml
packages/backend/src/server/api/endpoints/admin/unset-user-mutual-link.ts
packages/frontend/src/components/MkMediaImage.vue
packages/frontend/src/pages/admin-user.vue
packages/frontend/src/pages/settings/profile.vue
packages/frontend/src/pages/user/home.vue
packages/misskey-js/src/autogen/types.ts

上記のようにアップロードされた画像などをドライブに保存できる機能を追加しました
モデレーションで項目を個別で削除できるように
Fix: #699

Feat: 相互リンクの機能改善

---

packages/frontend/package.json
pnpm-lock.yaml

Update cropperjs to v2.0.0-rc.0

---

package.json
packages/misskey-js/package.json

Bump up version to 2024.5.0-io.2c

---

locales/en-US.yml
locales/ko-KR.yml

chore(i18n): Add saveThisFile for en-US, ko-KR

---

packages/frontend/src/components/MkMediaImage.vue
packages/frontend/src/pages/admin-user.vue

Fix(Frontend): このファイルをドライブに保存する が正常に機能しない問題を修正

---

package.json
packages/misskey-js/package.json

Bump up version to 2024.5.0-io.2d

---

locales/en-US.yml
locales/ko-KR.yml
package.json
packages/frontend/src/components/MkMediaImage.vue
packages/misskey-js/package.json

2024.5.0-host.2d

---

packages/backend/src/core/NoteCreateService.ts
packages/backend/src/misc/collapsed-queue.ts
packages/backend/src/queue/processors/InboxProcessorService.ts

`UPDATE instance` が渋滞する問題を解決します。
Redis に突っ込むのは面倒だったので in-process にキューを持って緩和することにします。

Defer instance metadata update

---

package.json
packages/misskey-js/package.json

Bump up version to 2024.5.0-io.2e

---

packages/backend/src/core/chart/charts/per-user-pv.ts
packages/backend/src/core/chart/core.ts
packages/backend/src/server/api/endpoints/users.ts

close #717
https://github.com/MisskeyIO/misskey/pull/717#issuecomment-2308354530

fix(api/users): ページビューの並び替えが正常に計算されない問題を修正

---

packages/backend/src/core/AntennaService.ts

fix(antenna): src=list && userListId=null の場合クエリータイムアウトが発生する問題を修正

---

packages/frontend/src/components/MkAutocomplete.vue
packages/frontend/src/components/MkSignin.vue
packages/frontend/src/components/MkUserSelectDialog.vue
packages/frontend/src/pages/api-console.vue

Input の変更から API を叩く箇所の debounce と AbortController の追加
MkSignin のログインで、user が取得できるまでログインがクリックできないようにした
パスワードマネージャの自動ログインが動かなくなるが、元々動作していなかったため問題ないと思われる

enhance(frontend): Input の変更から API を叩く箇所の debounce と AbortController の追加

---

packages/backend/src/core/NoteCreateService.ts
packages/backend/src/queue/processors/InboxProcessorService.ts

まだこけるので
https://github.com/MisskeyIO/misskey/actions/runs/10888141221/job/30211961872?pr=733

fix(backend/test): MisskeyIO#727 以降e2eテストがたまに失敗する問題を修正

---

.config/docker_example.yml
.devcontainer/devcontainer.yml
.devcontainer/docker-compose.yml
.dockerignore
.github/workflows/test-backend.yml
.gitignore
chart/templates/Deployment.yml
docker-compose.local-db.yml
docker-compose_example.yml
packages/backend/test/docker-compose.yml

Use DragonflyDB

---

packages/backend/src/server/api/endpoints/users.ts

fix(api/users): PVランキングに誰もいない場合エラーになる問題を修正

---

package.json
packages/misskey-js/package.json

Bump up version to 2024.5.0-io.2f

---

package.json
packages/misskey-js/package.json

Bump up version to 2024.5.0-io.2g

---

.github/workflows/api-misskey-js.yml
.github/workflows/lint.yml
.github/workflows/test-backend.yml
.github/workflows/test-frontend.yml
.github/workflows/test-misskey-js.yml
.github/workflows/test-production.yml
.github/workflows/validate-api-json.yml
package.json
packages/backend/src/server/api/SigninApiService.ts
packages/frontend/src/components/MkCaptcha.vue
packages/frontend/src/components/MkSignin.vue
packages/frontend/src/components/MkSignupDialog.form.vue
packages/misskey-js/package.json

2024.5.0-host.2g

---

packages/backend/src/server/sso/JWTIdentifyProviderService.ts

spec(SSO/JWT): トークンの有効期限を2週間に変更

---

packages/backend/src/config.ts
packages/backend/src/core/QueueModule.ts
packages/backend/src/misc/queues.ts
packages/backend/src/queue/QueueProcessorService.ts
packages/backend/src/server/web/ClientServerService.ts
packages/frontend/vite.config.local-dev.ts

enhance(queue): deliver queue を複数個設定できるようにする

---

package.json
packages/misskey-js/package.json

Bump up version to 2024.5.0-io.3

---

packages/backend/src/server/api/endpoints/admin/queue/deliver-delayed.ts
packages/backend/src/server/api/endpoints/admin/queue/inbox-delayed.ts

perf(backend): queue の delayed の件数が増えた際に deliver-delayed と inbox-delayed が返ってこなくなる問題を修正

---

packages/backend/src/server/web/ClientServerService.ts

spec(frontend): Bull Dashboard に relationship queue を追加

---

packages/backend/src/config.ts
packages/backend/src/core/QueueModule.ts
packages/backend/src/queue/QueueProcessorService.ts
packages/backend/src/server/web/ClientServerService.ts

enhance(queue): inbox と relationship にも MisskeyIO#745 を適用

---

packages/frontend/src/boot/main-boot.ts

spec(frontend): アカウント新規作成時のOOBE向上

---

package.json
packages/misskey-js/package.json

Bump up version to 2024.5.0-io.3a

---

packages/backend/src/server/sso/JWTIdentifyProviderService.ts
packages/backend/src/server/sso/SAMLIdentifyProviderService.ts
packages/backend/src/server/web/views/sso.pug
packages/frontend/src/pages/sso.vue

enhance(SSO): ユーザーに対話型プロンプトが表示されないように設定できるように

---

package.json
packages/misskey-js/package.json

Bump up version to 2024.5.0-io.3b

---

packages/frontend/src/components/MkCaptcha.vue

Turnstile が失敗、期限切れした際にコールバックに string が渡って成功扱いされてしまうのを修正

fix(frontend): Captcha のエラーハンドリングを修正

---

packages/frontend/src/components/MkReactionIcon.vue
packages/frontend/src/components/global/MkCustomEmoji.vue

fix(frontend/customemoji): リアクション以外の部分ではフォールバック画像にならないように

---

packages/frontend/src/components/MkNotifications.vue
packages/frontend/src/components/MkPagination.vue
packages/frontend/src/scripts/filter-muted-notification.ts
packages/frontend/src/ui/_common_/common.vue

feat(frontend/reactions): リアクションのミュートで通知からもミュートされるように

---

package.json
packages/misskey-js/package.json

Bump up version to 2024.5.0-io.3c

---

packages/backend/src/server/FileServerService.ts

https://github.com/misskey-dev/misskey/security/advisories/ghsa-gq5q-c77c-v236

security(ghsa-gq5q-c77c-v236): Block recursive proxy

---

package.json
packages/misskey-js/package.json

Bump up version to 2024.5.0-io.3d

---

packages/frontend/src/components/MkUserAnnouncementEditDialog.vue

fix(announcement): 個別ユーザーへのお知らせ編集ダイアログでチュートリアル受講のパラメータが反映されない問題を修正

---

packages/frontend/@types/vue-gtag.d.ts

fix(typescript): vue-gtagのタイプ定義の修正

---

package.json
packages/misskey-js/package.json

Bump up version to 2024.5.0-io.4

---

packages/frontend/src/scripts/usage-report.ts

feat(analytics): イベントの重複フィルターの修正

---

packages/backend/src/server/sso/SAMLIdentifyProviderService.ts

spec(SSO/SAML): Attribute追加

---

packages/frontend/src/account.ts
packages/frontend/src/boot/common.ts
packages/frontend/src/components/MkPageWindow.vue
packages/frontend/src/scripts/misskey-api.ts

feat(analytics): デッキUIのページ移動とAPIの応答時間のイベント実装

---

package.json
packages/misskey-js/package.json

Bump up version to 2024.5.0-io.4a

---

package.json
packages/misskey-js/package.json

Bump up version to 2024.5.0-io.4b

---

packages/frontend/src/scripts/get-note-menu.ts

fix(frontend): 引用RNの判定の条件が不完全だった問題を修正

---

package.json
packages/misskey-js/package.json

Bump up version to 2024.5.0-io.4c

---

packages/backend/src/server/api/endpoints/admin/abuse-report-resolver/update.ts

Cherry-picked from atsu1125/misskey-core@5001b4b77c8e12818e6c039d61b95eaea1b55be7

fix(about-report-resolver): 転送設定を一度有効にすると戻すことができない問題を修正

---

packages/frontend/src/components/MkAccountMoved.vue

fix(frontend): ユーザーのプロフィールページ閲覧時エラーが発生することがある問題を修正

---

packages/backend/src/core/EmailService.ts

spec(Email/Verifymail): MXレコードのドメインにもBANが適用されるように

---

packages/frontend/src/store.ts

spec(sound/note): デフォルトの他人の投稿の効果音をオフに

---

packages/frontend/src/components/MkGalleryPostPreview.vue
packages/frontend/src/pages/gallery/post.vue

ギャラリー一覧 のサムネイルをホバーしてもぼかしが外れないように
ギャラリーの説明を一番上に表示するように
会議で出てた

Enhance(Gallery): サムネイルをホバーしてもぼかしが外れないように & ギャラリーの説明を一番上に表示するように

---

packages/backend/src/core/FileInfoService.ts
packages/backend/src/decorators.ts
packages/backend/src/server/oauth/OAuth2ProviderService.ts
packages/backend/src/server/web/bios.css
packages/backend/src/server/web/boot.js
packages/backend/src/server/web/cli.css
packages/backend/src/server/web/flush.js
packages/backend/test-server/tsconfig.json
packages/backend/test/tsconfig.json
packages/backend/test/unit/ap-request.ts
packages/backend/tsconfig.json
packages/frontend/src/components/MkNote.vue
packages/frontend/src/components/MkNoteDetailed.vue
packages/frontend/src/components/MkPollEditor.vue
packages/frontend/src/unicode-emoji-indexes/en-US.json
packages/frontend/test/tsconfig.json
packages/frontend/tsconfig.json
packages/misskey-bubble-game/src/game.ts
packages/misskey-bubble-game/tsconfig.json
packages/misskey-js/tsconfig.json
packages/misskey-reversi/tsconfig.json
packages/sw/tsconfig.json

code cleanup

---

packages/frontend/src/navbar.ts

fix(frontend): instanceをimportし忘れてた

---

packages/frontend/src/pages/miauth.vue

Cherry-picked from TeamNijimiss/misskey@800359623e41a662551d774de15b0437b6849bb4

feat(MiAuth): アクセストークンの発行に失敗した場合コールバックに遷移しないようにする

---

packages/backend/src/core/FileInfoService.ts

enhance(backend): blurhash生成時、リサイズしてからRawに変換するように

---

.devcontainer/Dockerfile
.devcontainer/devcontainer.json
.devcontainer/init.sh
.dockerignore
.github/workflows/api-misskey-js.yml
.github/workflows/check-misskey-js-version.yml
.github/workflows/docker-beta.yml
.github/workflows/docker-host.yml
.github/workflows/docker-io.yml
.github/workflows/dockle.yml
.github/workflows/lint.yml
.github/workflows/test-backend.yml
.github/workflows/test-frontend.yml
.github/workflows/test-misskey-js.yml
.github/workflows/test-production.yml
.github/workflows/validate-api-json.yml
.gitignore
Dockerfile

chore(build): remove corepack & fetch gitmodules on checkout

---

packages/backend/migration/1735078824104-RoleAssignment-Memo.js
packages/backend/src/core/RoleService.ts
packages/backend/src/models/RoleAssignment.ts
packages/backend/src/server/api/endpoints/admin/roles/assign.ts
packages/backend/src/server/api/endpoints/admin/roles/users.ts
packages/backend/src/server/api/endpoints/admin/show-user.ts
packages/backend/src/types.ts
packages/backend/test/unit/RoleService.ts
packages/frontend/src/pages/admin-user.vue
packages/frontend/src/pages/admin/modlog.ModLog.vue
packages/frontend/src/pages/admin/roles.role.vue
packages/frontend/src/scripts/get-user-menu.ts
packages/misskey-js/src/autogen/types.ts
packages/misskey-js/src/consts.ts

enhance(role): ロールの割り当て時メモを残せるように

---

package.json
packages/misskey-js/package.json

Bump up version to 2024.5.0-io.5

---

package.json
packages/misskey-js/package.json

Bump up version to 2024.5.0-io.5a

---

packages/frontend/src/components/MkTimeline.vue

enhance(data-usage): remove GA timing report on fetch note json

---

packages/backend/src/server/api/stream/channels/antenna.ts
packages/backend/src/server/api/stream/channels/channel.ts
packages/backend/src/server/api/stream/channels/global-timeline.ts
packages/backend/src/server/api/stream/channels/home-timeline.ts
packages/backend/src/server/api/stream/channels/hybrid-timeline.ts
packages/backend/src/server/api/stream/channels/local-timeline.ts
packages/backend/src/server/api/stream/channels/role-timeline.ts
packages/backend/src/server/api/stream/channels/user-list.ts
packages/backend/test/utils.ts
packages/frontend/src/components/MkTimeline.vue
packages/frontend/src/scripts/merge.ts
packages/misskey-js/etc/misskey-js.api.md
packages/misskey-js/src/streaming.types.ts

fix(cdn-caching): 自分のリアクションが表示されない問題を修正

---

package.json
packages/misskey-js/package.json

Bump up version to 2024.5.0-io.5b

---

packages/frontend/src/components/MkMediaAudio.vue
packages/frontend/src/components/MkMediaVideo.vue
packages/frontend/src/index.html

fix(frontend/media): メディアプロキシ使用時オーディオが再生されない問題を修正

---

packages/backend/src/server/api/stream/channels/antenna.ts
packages/backend/src/server/api/stream/channels/channel.ts
packages/backend/src/server/api/stream/channels/global-timeline.ts
packages/backend/src/server/api/stream/channels/home-timeline.ts
packages/backend/src/server/api/stream/channels/hybrid-timeline.ts
packages/backend/src/server/api/stream/channels/local-timeline.ts
packages/backend/src/server/api/stream/channels/role-timeline.ts
packages/backend/src/server/api/stream/channels/user-list.ts

enhance(data-usage): ストリーム上で送るデータがない場合はオブジェクトごと省略するように

---

package.json
packages/misskey-js/package.json

Bump up version to 2024.5.0-io.5c

---

packages/frontend/src/components/MkVisitorDashboard.vue
packages/frontend/src/navbar.ts
packages/frontend/src/pages/about-misskey.vue
packages/frontend/src/pages/about.vue
packages/frontend/src/ui/_common_/navbar.vue

支援メニューがデッキUIで正常に動作しない問題を修正 + kawaiiモードのメニュー追加

fix(frontend): 支援メニューがデッキUIで正常に動作しない問題を修正

---

package.json
packages/misskey-js/package.json

Bump up version to 2024.5.0-io.5d

---

packages/frontend/src/store.ts

enhance(ux): defaultWithRepliesの既定値をtrueにする

---

.devcontainer/docker-compose.yml
.github/workflows/test-backend.yml
chart/templates/Deployment.yml
docker-compose.local-db.yml
docker-compose_example.yml
packages/backend/test/docker-compose.yml

This reverts commit 8c81bb9b6ac02a7a01848227e99922fab9392b86 partially.
lock_on_hashtags使用時フリーズする現象が回避できないのでallow-undeclared-keysに戻す、コードの変更は維持してCI等のフラグだけ戻しておく

Revert "perf(queue): BullMQ + DragonflyDB で Hashtag を使用しすべてをロックしないようにする (MisskeyIO#838)"

---

packages/frontend/src/pages/admin-user.vue
packages/frontend/src/pages/admin/roles.role.vue

fix(frontend/role): ロールの割り当て時メモを入力しないとキャンセル扱いされる問題を修正

---

packages/backend/src/core/UtilityService.ts

fix(backend/UtilityService): 非標準ポート番号環境でURIのローカル判定が常にfalseになる問題を修正

---

packages/backend/src/server/web/ClientServerService.ts

fix(backend/ClientServerService): リモートユーザーをユーザーIDで照会できない問題を修正

---

packages/backend/src/core/AccountMoveService.ts

fix(backend/AccountMoveService): アカウント引っ越しの際にモデレーションノートに空の改行が足される問題を修正

---

packages/backend/src/server/web/ClientServerService.ts

fix(backend/ClientServerService): 凍結されたユーザーをユーザーIDで照会できない問題を修正

---

package.json
packages/misskey-js/package.json

Bump up version to 2024.5.0-io.5e

---

packages/backend/src/server/web/ClientServerService.ts

fix(MisskeyIO#872): 消し忘れ

---

packages/frontend/src/scripts/get-user-menu.ts

fix(MisskeyIO#866): ユーザーメニューからロールの割り当て時メモを入力しないとキャンセル扱いされる問題を修正

---

packages/frontend/src/ui/_common_/navbar-for-mobile.vue

fix(frontend/mobile): モバイルでkawaiiモードが適用されない問題を修正

---

packages/backend/src/server/api/endpoints/notes/create.ts
packages/backend/src/server/web/cli.js
packages/frontend/src/components/MkPostForm.vue
packages/frontend/src/pages/reversi/game.vue
packages/frontend/src/scripts/get-note-menu.ts
packages/misskey-js/src/autogen/types.ts
packages/sw/src/sw.ts

spec(notes/create): 投稿されたnoteを返さないオプションを追加

---

packages/backend/src/core/chart/ChartManagementService.ts
packages/backend/src/queue/processors/CleanChartsProcessorService.ts
packages/backend/src/queue/processors/ResyncChartsProcessorService.ts
packages/backend/src/queue/processors/TickChartsProcessorService.ts

(cherry picked from https://activitypub.software/TransFem-org/Sharkey/-/merge_requests/830)

Sync charts one-at-a-time to reduce database contention and timeouts

---

locales/en-US.yml
locales/index.d.ts
locales/ja-JP.yml
locales/ko-KR.yml
packages/frontend/src/components/MkDraftsDialog.vue
packages/frontend/src/components/MkPostForm.vue
packages/frontend/src/pages/settings/general.vue
packages/frontend/src/pages/settings/preferences-backups.vue
packages/frontend/src/store.ts
packages/frontend/src/types/note-draft-item.ts

- 保存されている下書きの一覧を確認・選択・削除できる機能の追加
- 投稿フォームを開いたときに下書きを自動で読み込むかどうか選べるように
- これを自動で読み込まないようにすると複数個の下書きを保存できる
- 自動で読み込むように設定を戻した場合複数個保存されていた場合は新しい順でロードする

feat(frontend/draft): 下書き機能の改良・強化

---

package.json
packages/misskey-js/package.json

Bump up version to 2024.5.0-io.6

---

packages/frontend/src/components/MkPostForm.vue

spec(MisskeyIO#884): 送信ボタンをアイコンのみの表示にするしきい値を変更

---

packages/frontend/src/components/MkPostForm.vue

spec(MisskeyIO#884): 送信ボタンをアイコンのみの表示にするしきい値を変更 2

---

package.json
packages/misskey-js/package.json

Bump up version to 2024.5.0-io.6a

---

package.json
packages/misskey-js/package.json

Bump up version to 2024.5.0-io.7

---

packages/backend/src/core/S3Service.ts

Cloudflare R2 does not support 'x-amz-checksum-*'

fix(backend/object-storage): disable data integrity protections

---

package.json
packages/misskey-js/package.json

Bump up version to 2024.5.0-io.7a

---

packages/frontend/src/components/MkDraftsDialog.vue

fix(frontend/MkDraftsDialog): :art:

---

package.json
packages/misskey-js/package.json

Bump up version to 2024.5.0-io.7b

---

packages/backend/src/server/api/SigninApiService.ts
packages/frontend/src/os.ts

fix(backend/SigninApiService): ログインのレートリミット時、意図したものと違うエラーメッセージが表示される可能性がある問題を修正

---

packages/frontend/src/components/MkPostForm.vue

enhance(ux/frontend/MkPostForm): 予約投稿の時間を再度設定する時、以前設定した時間が表示されるように

---

packages/backend/src/queue/processors/CheckMissingScheduledNoteProcessorService.ts

spec(backend/queue/ScheduledNote): 予約時間が過ぎる前にチェックするように

---

locales/en-US.yml
locales/index.d.ts
locales/ja-JP.yml
locales/ko-KR.yml
packages/backend/src/core/NoteCreateService.ts
packages/backend/src/core/RoleService.ts
packages/backend/src/models/json-schema/role.ts
packages/backend/src/server/api/endpoints/notes/create.ts
packages/frontend/src/components/MkPostForm.vue
packages/frontend/src/const.ts
packages/frontend/src/pages/admin/roles.editor.vue
packages/frontend/src/pages/admin/roles.vue
packages/misskey-js/src/autogen/types.ts

spec(role/ScheduledNote): ロールで予約投稿の個数・予約の最大日数を制御できるように

---

packages/backend/src/server/api/stream/channels/antenna.ts
packages/backend/src/server/api/stream/channels/channel.ts
packages/backend/src/server/api/stream/channels/global-timeline.ts
packages/backend/src/server/api/stream/channels/hashtag.ts
packages/backend/src/server/api/stream/channels/home-timeline.ts
packages/backend/src/server/api/stream/channels/hybrid-timeline.ts
packages/backend/src/server/api/stream/channels/local-timeline.ts
packages/backend/src/server/api/stream/channels/main.ts
packages/backend/src/server/api/stream/channels/role-timeline.ts
packages/backend/src/server/api/stream/channels/user-list.ts
packages/frontend/src/scripts/use-note-capture.ts

perf(stream): 必要のない既読処理のメッセージが発生しないように

---

package.json
packages/misskey-js/package.json

Bump up version to 2024.5.0-io.7c

---

packages/frontend/src/scripts/use-note-capture.ts

fix(MisskeyIO#907): サブスクライブコマンドは必要だった

---

packages/frontend/src/store.ts

spec(frontend/ad): 常に広告を表示するの既定値を有効に

---

packages/frontend/src/components/MkNote.vue
packages/frontend/src/components/MkNotification.vue

perf(frontend): contain-intrinsic-size のwidthの保存をやめる

---

packages/backend/src/core/RoleService.ts
packages/backend/src/core/entities/UserEntityService.ts
packages/backend/src/server/api/StreamingApiServerService.ts
packages/backend/src/server/api/stream/Connection.ts
packages/backend/src/server/api/stream/channel.ts
packages/backend/src/server/api/stream/channels/antenna.ts
packages/backend/src/server/api/stream/channels/channel.ts
packages/backend/src/server/api/stream/channels/global-timeline.ts
packages/backend/src/server/api/stream/channels/home-timeline.ts
packages/backend/src/server/api/stream/channels/hybrid-timeline.ts
packages/backend/src/server/api/stream/channels/local-timeline.ts
packages/backend/src/server/api/stream/channels/role-timeline.ts
packages/backend/src/server/api/stream/channels/user-list.ts
packages/frontend/src/components/MkTimeline.vue

spec(backend/stream): モデレーターにも一般ユーザーと同じく通常の投稿はcdn経由で配信するように

---

packages/backend/src/core/entities/DriveFileEntityService.ts
packages/backend/src/server/FileServerService.ts
packages/backend/src/server/ServerService.ts
packages/backend/src/server/web/UrlPreviewService.ts
packages/frontend/src/scripts/media-proxy.ts

spec(media-proxy): urlをクエリではなくパラメータで指定するように

---

packages/backend/src/postgres.ts

chore(database/log): DBへのクエリーログをverboseモードでのみ出力するように

---

packages/frontend/src/pages/gallery/post.vue

ギャラリーの画像に対するCSSセレクターが不正でスタイルが壊れている問題の修正

fix(frontend/gallery): 画像のスタイルが壊れている問題の修正

---

package.json
packages/misskey-js/package.json

Bump up version to 2024.5.0-io.8

---

packages/frontend/src/account.ts

cherry picked from upstream

---

packages/backend/src/server/web/views/base.pug
packages/frontend/.storybook/preview-head.html
packages/frontend/src/components/MkMediaAudio.vue
packages/frontend/src/components/MkMediaVideo.vue
packages/frontend/src/components/MkNote.vue
packages/frontend/src/components/MkNoteDetailed.vue
packages/frontend/src/pages/reversi/game.setting.vue
packages/frontend/src/style.scss

perf(frontend/tabler-icons): アイコンの読み込みに異常に時間がかかる問題の緩和

---

packages/backend/src/server/web/views/base.pug
packages/frontend/.storybook/preview-head.html
packages/frontend/src/style.scss
scripts/build-assets.mjs

fix(MisskeyIO#927): tabler-icons-filledのフォントを参照できない問題を修正

---

packages/backend/src/server/ServerService.ts

spec(backend/fastify): set maxParamLength to 1024

---

package.json
packages/misskey-js/package.json

Bump up version to 2024.5.0-io.8a

---

packages/backend/src/core/DriveService.ts

手元でopusをアップロードして再生できることは確認してます
それ以外の画像のアップロード等も正常にできることも確認してます

fix(backend/DriveService): variationが付いたMIMEを正常にパースできるように

---

packages/frontend/src/components/MkDateSeparatedList.vue
packages/frontend/src/scripts/get-note-menu.ts

fix: MSKY-77

---

packages/frontend/src/components/MkDateSeparatedList.vue
packages/frontend/src/style.scss

fix(MisskeyIO#956): MSKY-77

---

package.json
packages/misskey-js/package.json

Bump up version to 2024.5.0-io.9a

---

package.json
packages/misskey-js/package.json

Bump up version to 2024.5.0-io.9d

---

package.json
packages/misskey-js/package.json

Bump up version to 2024.5.0-io.9e

---

.github/workflows/check-misskey-js-version.yml
.github/workflows/docker-io.yml
.github/workflows/dockle.yml
.github/workflows/lint.yml
.github/workflows/test-backend.yml
.github/workflows/test-frontend.yml
.github/workflows/test-misskey-js.yml
.github/workflows/test-production.yml
.github/workflows/validate-api-json.yml

chore(git): デフォルトブランチの名前をmainに変更

---

.github/workflows/check-misskey-js-version.yml
package.json
packages/backend/src/core/ImageProcessingService.ts
packages/misskey-js/package.json
pnpm-lock.yaml

2024.5.0-io.10

---

package.json
packages/misskey-js/package.json

Bump up version to 2024.5.0-io.10

---

package.json
packages/misskey-js/package.json

Bump up version to 2024.5.0-host.10

---

packages/backend/src/server/web/views/base.pug

MSKY-153: tabler-icon-outline/filled がロードされない問題を修正
