MisskeyIO/misskey

packages/backend/src/misc/id/aid.ts, packages/backend/src/server/api/endpoints/notes/timeline.ts
- IDがタイムスタンプベースで生成されていることを利用し、createdAtではなくidで絞り込むように変更
- createdAtによる絞り込みが結構遅いので
- ローカルでホームタイムラインが正常に取得できるところまで確認済み
=> ホームタイムライン取得時にcreatedAtではなくidで絞り込むように

packages/backend/src/server/api/endpoints/notes/timeline.ts
Home Timeline の構築で用いている `take()` を `limit()` に置き換えます。
クエリパフェーマンスの向上がねらいです。
投稿 note 数の少ないユーザーばかりをフォローしているユーザーにおいて、特に改善幅が大きいです。
複雑な JOIN を含むクエリで take() を用いると、ベーステーブルの行の増幅を避けるために TypeORM が DISTINCT つきのクエリを自動で発行します。
この DISTINCT つきクエリはパフォーマンスへのインパクトが大きく、行の増幅が起きないクエリでは省略すべきです。
現状の Home Timeline のクエリでは行の増幅が起きるような JOIN はしておらず、省略可能です。
明示的に省略する場合は take() ではなく limit() を使います。
参考: https://github.com/typeorm/typeorm/blob/58fc08840a4a64ca1935391f4709a784c3f0b373/docs/select-query-builder.md#using-pagination
@Ry0taK 念のためテストしていただけると嬉しいです。直近でこの周辺のクエリを触っていたようなのでセカンドオピニオンとして適切だろうと思ってメンションしています。
=> Use limit() instead of take() because take() produces needless DISTINCT

packages/frontend/src/style.scss
iOSのブラウザで画面を回転させてもテキストサイズが変わらないようにする。
https://redirect.github.com/misskey-dev/misskey/pull/11487
=> fix(frontend): webkit-text-size-adjustを100%に固定する

packages/frontend/package.json, packages/frontend/vite.config.ts, pnpm-lock.yaml
@rollup/plugin-typescript を入れる
何かの拍子でviteのrollupに設定してる`input { app: './src/_boot_.ts' }`がトランスパイルされてないままboot.jsに入ってしまい、APP_IMPORTエラーでフロントエンドが全く動かないことになる現象がある
（実際DevToolsでネットワークタブをみると`/vite/_boot_ts`をリクエストして404をもらってる感じ）
viteとrollupのビルドパイプライン上typescriptを処理してるのはvue-tscだけみたいだったので、
vueじゃないtypescriptは誰が処理してくれてるのかというと・・・vue-tscぽいので
viteがvue-tscを呼び出してくれない状態（なんでかはわからない）だと`.ts`がトランスパイルされないみたい
普通にtypescriptモジュールをrollupのビルドに入れて上げれば直るでしょと思って入れたらうまくいったって感じです
=> fix: たまに`./src/_boot_.ts`がトランスパイルされない問題を修正

Dockerfile
https://redirect.github.com/misskey-dev/misskey/issues/10984#issuecomment-1672495555
https://sharp.pixelplumbing.com/install#linux-memory-allocator
https://redirect.github.com/nodejs/node/issues/21973
=> enhance: メモリアロケーターをjemallocにする

packages/backend/src/core/SearchService.ts
起動時にMeiliSearchの設定を更新しないようにする
インデックス設定を更新すると再インデックスタスクが走るので、MeiliSearchが重たくなるため
> WARNING
Updating searchable attributes will re-index all documents in the index, which can take some time. We recommend updating your index settings first and then adding documents as this reduces RAM consumption.
https://www.meilisearch.com/docs/reference/api/settings#searchable-attributes
TODO: MeiliSearch再構築・アップデート時に以下のようなリクエストを投げる必要がある
```
curl \
-X PATCH 'http://localhost:7700/indexes/movies/settings' \
-H 'Content-Type: application/json' \
--data-binary '{
"searchableAttributes": [
"text",
"cw"
],
"filterableAttributes": [
"channelId",
"createdAt",
"tags",
"userHost",
"userId"
],
"sortableAttributes": [
"createdAt"
],
"typoTolerance": {
"enabled": false
},
"pagination": {
"maxTotalHits": 10000
}
}'
```
=> perf: 起動時にMeiliSearchの設定を更新しないようにする

packages/backend/src/GlobalModule.ts, packages/backend/src/boot/index.ts
まだプライマリープロセスが終わらないことがある
DB接続が切れたら何もできるはずがないので、確実に終了するようにイベントを呼ぶ
nestjsがおかしいかも
裏は全く取れてないけど個人的にはQueueProcessorServiceが怪しい
（Masterでは使われないのでそもそも呼び出されないが、handlerはあるのでこれが終わるのを待ってるとか？）
タスクマネージャからプライマリープロセスを終了させようとすると反応しないのが直った
プライマリープロセスがシャットダウン中のみワーカープロセスが再起動しないようにした
=> enhance: シグナルを受け、DB接続が切れたら確実に終了させる

packages/backend/src/core/entities/NoteReactionEntityService.ts, packages/backend/src/server/api/endpoints/drive/files/find.ts, packages/backend/src/server/api/endpoints/notes/reactions.ts, packages/backend/src/server/api/endpoints/users/reactions.ts, packages/backend/src/server/api/endpoints/users/show.ts
* z-6561で報告された不具合の修正
- リアクションの一覧とユーザーリストが正常に表示されないとの報告
* リアクションに関するものについては #134 でNoteReactionEntityServiceのことをケアしてなかったのが原因
* ユーザーリストに関しては`users/show`で凍結されたユーザーがある場合リストに存在しないユーザーが表示されてしまうバグが元からあった模様
=> 凍結されたユーザーが含まれている場合一部の機能が誤動作する不具合を修正

packages/backend/src/server/api/endpoints/admin/queue/deliver-delayed.ts, packages/backend/src/server/api/endpoints/admin/queue/inbox-delayed.ts
エラーログを作ってる途中で`job.data`が`undefined`というエラーになってるので、`data`の中身を全部`JSON.stringify`するようにした
https://github.com/MisskeyIO/misskey/pull/164 で、単純にエンドポイントURLのパースに失敗した場合の対応はできたけど
`job.data`が丸ごと`undefined`だったり期待通りのプロパティが存在しなかったりする場合はまだこける
=> キューに予期しないデータが入っている場合、エンドポイントURLのパースもエラーログの作成も失敗する問題を修正

packages/backend/src/postgres.ts
クエリが slow であると判定される閾値を 300ms から 10s に伸ばします。
300ms を閾値とすると、あまりに多くのクエリが slow 判定され、あまりに多くの slow query log が出力されてしまい、パフォーマンス分析の際にノイズになるため。
io では pg_stat_statements 等を用いて slow query を分析できるため、アプリケーションレベルで閾値の厳しいログを吐く意味はない。
=> Extend slow query threshold to reduce logs

packages/backend/src/misc/cache.ts
Memory 上の lifetime(TTL) は切れたが、Redis 上の lifetime はまだ切れていないという状況で、Redis から読み取った値を MemoryCache に書き戻します。
現状、Redis + MemoryCache の2層キャッシュである RedisSingleCache において、MemoryCache 上の lifetime(TTL) は切れたが、Redis 上の lifetime はまだ切れていないという状況で、都度 Redis へのリクエストと Redis からのレスポンスのパースが走ってしまいます。
（つまり、MemoryCache が仕事をしなくなってしまう）
この影響で、CustomEmojiService ではキャッシュを書いた3分後からの27([=30-3](https://github.com/MisskeyIO/misskey/blob/760fe8cfcc4e08d05d7e4501219c3638fa56d3a1/packages/backend/src/core/CustomEmojiService.ts#L51-L52))分間は Redis へのクエリと JSON.parse が大爆発するボーナスタイムになっています。
このパッチはこれを解決します。
Redis 上での残り lifetime を考慮せずに MemoryCache に書き戻してしまうため、実際の lifetime が lifetime + memoryCacheLifetime となります。
たとえば CustomEmojiService では従来30分間の lifetime だったところ、このパッチの影響で33分間キャッシュされることになります。
=> Hot-fix: Write-back value in memory when it's available in redis

packages/backend/src/core/entities/NoteEntityService.ts, packages/backend/src/misc/loader.ts, packages/backend/test/unit/misc/loader.ts
- PubSub の notesStream のイベント受信時のクエリ発行数を削減し、app/DB 共に負荷を削減します
- 同 microtask 内で呼び出された `notesRepository.findOneOrFail` をバッファリングし、同じ id へのクエリを1つにまとめます（debounce）
- debounce 処理を行う DebounceLoader を実装し、追加します
PubSub から notesStream のイベントを受信すると、そのプロセスが担当しているクライアントのコネクション数の分だけ `NoteEntityService.pack` が呼び出されます。
（正確には、その note に replyId や renoteId が付いている場合）
つまり、同一 noteId に対するクエリがクライアント数と同じ量発射されます。
当然これはあまりに無駄で、実際に WebSocket を担当するプロセスの CPU 使用率が断続的に数秒間100%に貼り付くといったパフォーマンスの問題も起きているため、これを解消したいと考えました。
NoteEntityService のテストが困難なので、ちょっと検証が足りてないかも。
DebounceLoader のユニットテストは書いたし通ったので、たぶん動く……
=> Debounce SQL in note pack

packages/backend/src/core/entities/NoteEntityService.ts
タイトル通り
streaming から Note の pack を行う際に populateEmojis から大量にクエリが飛ぶのを回避する
prefetchEmojis ではキャッシュ済みのものを除外しているため、packMany が呼ばれた場合でも大量にクエリが飛ぶことはない
=> NoteEntityService の pack 内で CustomEmojiService の prefetchEmojis を呼ぶ

packages/backend/src/core/FetchInstanceMetadataService.ts
fetchInstanceMetadataのmutexを時間が経ったら自動でexpireされるようにする
外部サーバー情報が更新されないとの報告 z-7719
misskey-dev#11128 のサイドエフェクトである
=> fetchInstanceMetadataの処理中にサーバーが強制終了された場合Lockが永遠に解除されない問題を修正

packages/backend/src/core/activitypub/ApRendererService.ts, packages/backend/src/core/activitypub/models/ApPersonService.ts, packages/backend/src/core/activitypub/type.ts
プロフのMFMを連合するようになる
本家にマージされてしまった＆コードを見た感じ動きそうだったので
misskey-dev#12184
misskey-dev#12185
=> fix(backend): プロフィールの自己紹介欄のMFMを連合するように (misskey-dev#12184)

packages/frontend/src/components/MkEmojiPicker.section.vue, packages/frontend/src/components/MkEmojiPicker.vue
=> 絵文字ピッカーのカテゴリの階層を表示するように・サブカテゴリを絵文字より上に

packages/frontend/src/components/MkEmojiPicker.section.vue, packages/frontend/src/components/MkEmojiPicker.vue, packages/frontend/src/scripts/emojilist.ts
半角スペースで囲まれたスラッシュ(` / `)のみフォルダ構造になるように
長いカテゴリ名を狭いウィンドウで見る場合改行されるように
セクションの背景の追加
カテゴリの名前として/を使いたい場合はあるため
ioカスタム絵文字モデレーションチームの要請
=> 絵文字ピッカーのカテゴリのフォルダ分けの条件の変更・長いカテゴリ名の表示調整・セクションの背景の追加

locales/index.d.ts, locales/ja-JP.yml, packages/backend/migration/1699284486293-urlPreviewDenyList.js, packages/backend/src/models/entities/Meta.ts, packages/backend/src/server/api/endpoints/admin/meta.ts, packages/backend/src/server/api/endpoints/admin/update-meta.ts, packages/backend/src/server/web/UrlPreviewService.ts, packages/frontend/src/components/MkUrlPreview.vue, packages/frontend/src/pages/admin/moderation.vue, packages/misskey-js/etc/misskey-js.api.md, packages/misskey-js/src/entities.ts
指定したパターンに一致したURLのプレビューのサムネイルを隠す機能
URLプレビューのサムネイルがセンシティブであるという通報が多いため、負担軽減
=> URLプレビューのサムネイルを隠す機能を追加

packages/frontend/src/components/MkPullToRefresh.vue
横方向にスワイプしている際には引っ張っている判定にならないように
縦に長い操作をしている時のみPullと見なす
スクロールして最上段に到達した場合すぐ引っ張って更新ができるように
横方向のスワイプに関してはスマホでデッキUIを利用する場合すごい不便らしい
iOSなどのPullToRefreshの挙動にできる限り近づける
=> enhance(frontend): PullToRefreshの改善

packages/frontend/src/pages/timeline.vue
モバイル環境でタイムラインの上段メニューに空のボタンが追加されている問題を修正
デスクトップ環境用のリロードボタンの代わりに空のobjectを渡してしまっているため空のボタンが登録されていた
=> fix(frontend): モバイル環境でタイムラインの上段メニューに空のボタンが追加されている問題を修正

packages/frontend/src/components/MkEmojiPicker.vue
とても長い絵文字のカテゴリの名前が
「とてもながいえもじのかてごりのなまえ」から
「…かてごりのなまえ」になる（ウィンドウの幅による）
リスト内に前の部分が同じ文字列がめちゃくちゃ並ぶので省略しちゃったほうが分かりやすいのではと思ったため
~~スマホ編集なのでテストできてない~~
期待通りの挙動をしてた
=> enhance(frontend): 絵文字ピッカーで長いカテゴリの名前を前の部分から省略して表示するように

packages/frontend/src/components/MkEmojiPicker.vue
This reverts commit 5421f4f377aed8fe32b8d21ce17b17392933f502.
MisskeyIO#223 のrevert
カテゴリ名に数字が含まれると予期しない挙動になるため
=> Revert "enhance(frontend): 絵文字ピッカーで長いカテゴリの名前を前の部分から省略して表示するように (MisskeyIO#223)

packages/frontend/src/components/MkPullToRefresh.vue
たまにTL画面からユーザープロフィール画面に移動した時上方向のタッチ操作ができなくなる問題を修正（したい）
なぜか後ろにあるはずのMkPullToRefreshのhandlerが動いて邪魔になっていると思うので
onDeactivatedもしくはonUnmountedイベント発生時に更新中フラグを立てて何もしないようにする
=> enhance(frontend/PullToRefresh): コンポーネントがDOMから消えた時点でタッチ操作などのコールバック関数が止まるように

packages/frontend/src/pages/user/index.files.vue
=> fix(frontend): ユーザーページのファイル一覧のセンシティブとして設定されたファイルの表示がおかしい問題を修正

packages/backend/src/core/NoteCreateService.ts, packages/backend/src/server/api/endpoints/users/notes.ts
ユーザープロフィールページのノートタブのファイル付きタブでファイル付きではないチャンネル投稿とリプライが混ざってしまう問題を修正
=> fix(backend): ユーザータイムラインのファイル付きフィルター機能がリプライやチャンネルの投稿にも適用されるように

packages/backend/src/server/api/endpoints/i/2fa/key-done.ts, packages/backend/src/server/api/endpoints/i/2fa/register-key.ts, packages/backend/src/server/api/endpoints/i/2fa/register.ts, packages/backend/src/server/api/endpoints/i/2fa/remove-key.ts, packages/backend/src/server/api/endpoints/i/2fa/unregister.ts, packages/backend/src/server/api/endpoints/i/change-password.ts, packages/backend/src/server/api/endpoints/i/delete-account.ts, packages/backend/src/server/api/endpoints/i/update-email.ts
追加認証（パスワードと2FA）の必要なAPIで認証が失敗した場合APIのエラー定義が甘いせいでAPIのエラーハンドリングの仕様上ユーザーに渡る応答にはサーバー側のエラーとしか返されないのをちゃんとしたエラーコードが返されるようにする
* 追加認証に失敗したのがサーバーの問題だと思われてしまう、ユーザーは実際に何が間違ってるかわからないため
* nginx上5xxのエラーと扱われてしまいリトライが走ってしまうため
cc: @syuilo 
この変更のチェリーピックを検討する他のフォークの方へ
　ioフォークでは[ApiCallService](https://github.com/MisskeyIO/misskey/blob/2023.11.1-io.1b/packages/backend/src/server/api/ApiCallService.ts#L366)で`IdentifiableError`も`ApiError`と同様にエラーそのまま応答として返すようになっています。ご注意ください。
=> fix(backend): 追加認証の必要なAPIの認証失敗がサーバーエラーとして返されてしまう問題を修正

packages/frontend/src/components/MkAutocomplete.vue
* 実際は同じ絵文字なら重複してサジェストに出ないように
* エイリアスではない絵文字>前方一致>部分一致>あいまい検索順で表示されるようになるように
期待通りの検索結果になっていない場合が多いため
cc: @syuilo
=> enhance(frontend): 絵文字のオートコンプリートのアルゴリズムの改善

packages/backend/src/GlobalModule.ts, packages/backend/src/core/QueueModule.ts, packages/backend/src/daemons/QueueStatsService.ts, packages/backend/src/di-symbols.ts, packages/backend/src/queue/QueueProcessorService.ts, packages/backend/src/queue/const.ts
redisForJobQueue の接続を使い回すようにする
コネクション数が爆発しないように
https://docs.bullmq.io/guide/connections
=> redisForJobQueue の接続を使い回す

packages/backend/src/GlobalModule.ts
redisForJobQueue の maxRetriesPerRequest を null にする
null にしろと警告が出るので
元のコネクションを直接渡さなかった場合の挙動は null になるみたいなので、問題ないと思われる
https://github.com/taskforcesh/bullmq/blob/v4.13.3/src/classes/redis-connection.ts#L78
=> redisForJobQueue の maxRetriesPerRequest を null にする

packages/frontend/src/components/MkGoogle.vue, packages/frontend/src/components/MkLink.vue, packages/frontend/src/components/MkPageWindow.vue, packages/frontend/src/components/MkVisitorDashboard.vue, packages/frontend/src/components/global/MkA.vue, packages/frontend/src/components/global/MkUrl.vue, packages/frontend/src/pages/admin-file.vue, packages/frontend/src/pages/admin/queue.vue, packages/frontend/src/pages/instance-info.vue, packages/frontend/src/plugin.ts, packages/frontend/src/scripts/get-note-menu.ts, packages/frontend/src/ui/_common_/common.ts
noopenerオプションがつけられてない所に全部noopenerオプションを付ける
開かれたのページからwindow.openerでmisskeyにアクセスできてしまう恐れがあるため
cc: @syuilo
=> enhance(frontend): window.openやaタグにnoopenerオプションをつける

packages/frontend/src/components/MkEmojiPickerWindow.vue, packages/frontend/src/components/MkPostForm.vue, packages/frontend/src/os.ts, packages/frontend/src/pages/admin/announcements.vue
投稿フォームで絵文字ボタンを押すと従来通り絵文字ピッカーのウィンドウが開くように
お知らせの絵文字ボタンでも同じ挙動になるように
ioモデレーションチーム要請
=> fix(EmojiPicker): 投稿フォームで絵文字ボタンを押すと従来通り絵文字ピッカーのウィンドウが開くように

packages/backend/src/core/QueueService.ts, packages/backend/src/server/ActivityPubServerService.ts
`as タイプ`の結果をそのまま渡すのではなくチェックを入れたりをもそも`as`を使わないようにした
queueにdataフィールドが空のジョブが登録され、ずっとエラーになるため
=> fix(Queue): InboxやDeliverキューにdataフィールドが空のジョブが登録されないように

Dockerfile
Docker イメージビルド時の pnpm i 後に pnpm rebuild を実行するように
各依存関係の postinstall 等が走るステージが native-builder と target-builder のどちらか(タイミング次第)であり、native-builder のみで走った場合に一部の機能が動かないため
Closes MisskeyIO#316
=> Docker イメージビルド時の pnpm i 後に pnpm rebuild を実行するように

packages/backend/package.json, pnpm-lock.yaml
ジョブキューのlockが上手く取れない問題の続き
2023.11.x時点までは正常動作していたと思うので、11月のbullmqでlockに関する記載のある
https://redirect.github.com/taskforcesh/bullmq/releases/tag/v4.12.8
```
Bug Fixes
worker: keep extending locks while closing workers
```
の１つ前のバージョンにダウングレードさせてみる
=> deps(backend): Downgrade BullMQ to 4.12.7

packages/backend/src/config.ts, packages/backend/src/postgres.ts
DBのクエリーのキャッシュに使われるRedisの設定を分ける
DBクエリーいっぱい飛び交う時メインのRedisが固まる現象の回避のため
=> enhance(PostgreSQL): DBのクエリーのキャッシュに使われるRedisの設定を分ける

packages/backend/src/boot/common.ts, packages/backend/src/daemons/QueueStatsService.ts
- Queue Stats の数字が "Process" 以外もとに戻ります
- Queue Stats の数字はほしい
- "Process" の数字を計算するには Redis Streams を subscribe する必要がある
- パフォーマンスインパクトが大きすぎる
- "Process" は0で固定し、それ以外を復活させる
=> Remove "process" queue stat counter for performance

packages/backend/src/logger.ts
fix bug from MisskeyIO#346
`context`の値が`[object Object].[object Object]`と出てしまっているため
=> fix: MK_LOG_JSONのcontextの値が正常に表示されない問題を修正

packages/frontend/src/pages/drop-and-fusion.vue, packages/frontend/src/scripts/drop-and-fusion-engine.ts
本家の更新のコミットもついでに入れた
ゲーム中なら諦める、ゲームオーバー画面の表示中はリスタートになるように
一部の値がゲーム終了時初期化されていないのも直した
リトライって書いてあるにもかかわらずリトライができないボタンになっていたので
cc: @syuilo
=> fix(drop-and-fusion): バブルゲームのリトライボタンでリトライができない問題を修正

packages/backend/src/core/NoteCreateService.ts, packages/backend/src/core/PollService.ts, packages/backend/src/core/QueueService.ts, packages/backend/src/core/activitypub/ApInboxService.ts, packages/backend/src/core/activitypub/models/ApNoteService.ts, packages/backend/src/queue/processors/InboxProcessorService.ts, packages/backend/src/queue/types.ts, packages/backend/src/server/ActivityPubServerService.ts
Fedibirdのサークル、Hubzillaの限定公開タイプのPostの場合、
公開範囲`specified`のアクティビティがそれぞれのユーザーの個別inboxに届く仕様になっているため、
個別のinboxに届いたPostをそのユーザーが見れない場合は`visibleUserIds`を更新し、タイムラインや通知などの処理を行う
resolves MisskeyIO#354
https://misskey.io/notes/9odvrk1kagpl003v
=> spec(ActivityPub): 個別ユーザーのinboxに届いた限定公開のPostはそのユーザーに閲覧権限があると見なす

packages/backend/src/core/NoteCreateService.ts
Fedibirdのサークルは相互フォロー限定公開みたいな意味合いなので別にメンションではないらしい
メンションされていないのに通知が作成されてしまい困惑することがあるらしいので
related: MisskeyIO#361
=> spec(ActivityPub): メンションされていない場合は個別ユーザーのinboxに届いた限定公開のPostは通知を作成しないように

packages/backend/migration/1705475608437-reversi.js, packages/backend/migration/1706011243939-UserProfileBirthdayIndex.js
=> fix(migration): DBのマイグレーションの修正

packages/backend/src/server/api/endpoints/notes/hybrid-timeline.ts, packages/backend/src/server/api/endpoints/notes/local-timeline.ts, packages/backend/src/server/api/endpoints/users/notes.ts, packages/backend/src/server/api/stream/channels/global-timeline.ts
=> fix(timeline): `withReplies`と`withFiles`を両方設定できない問題を修正

packages/backend/src/server/api/endpoints/notes/mentions.ts
@mentionされていないノートがあなた宛てに載ってしまう問題を修正
通常のspecified投稿の場合、visibleUserIdsはmentionsに含まれるので、このクエリーでvisibleUserIdsを参照する必要はない
=> fix(backend/notes/mentions): @mentionされていないノートがあなた宛てに載ってしまう問題を修正

packages/frontend/src/components/MkColorInput.vue, packages/frontend/src/components/MkDrive.vue, packages/frontend/src/components/MkEmojiPicker.vue, packages/frontend/src/components/MkGoogle.vue, packages/frontend/src/components/MkInput.vue, packages/frontend/src/components/MkMediaList.vue, packages/frontend/src/components/MkMediaRange.vue, packages/frontend/src/components/MkPostForm.vue, packages/frontend/src/components/MkRadio.vue, packages/frontend/src/components/MkSwitch.vue, packages/frontend/src/pages/admin/ads.vue, packages/frontend/src/pages/oauth.vue, packages/frontend/src/pages/settings/theme.vue
Chromeのパスワードマネージャーにあらゆる入力欄がパスワード扱いをさせる問題を回避
1. inputタグにタイプ別に違うクラスを割り当て、ヒューリスティックアルゴリズムが違うものであることを区別できるように
2. `pw`のフィールドだと判定される要素を一つでも減らせる
~なんと、全くテストしておりません~
=> fix(frontend): Chromeのパスワードマネージャーにあらゆる入力欄がパスワード扱いをさせる問題を回避

packages/backend/src/server/api/endpoints/notes/create.ts, packages/backend/test/e2e/antennas.ts, packages/backend/test/e2e/note.ts, packages/backend/test/e2e/renote-mute.ts, packages/backend/test/e2e/streaming.ts, packages/backend/test/utils.ts
冪等性ぽい処理
ユーザーidと`notes/create`のリクエストのhashをキーとして、処理中・処理されたノートのidをキャッシュする
キャッシュされているノートのidが存在しないノートの場合は新規として処理する
nginx側でリクエストのリトライを設定している場合、ネットワーク不安定・高負荷時ノートが重複して投稿されてしまうため
=> spec(backend/notes/create): ネットワーク不安定・高負荷時ノートが重複して投稿される問題を修正

packages/backend/src/server/api/endpoints/notifications/create.ts
Cloudflare上でレートリミットをコントロールしたいため
=> spec(api): Misskey内部の`notifications/create`のレートリミットを廃止

packages/backend/src/logger.ts
=> fix(backend/logger): `context`の引数を渡すとloggerに設定されたcontextが上書きされてしまう問題を修正

packages/backend/src/core/NoteCreateService.ts
Cherry-picked from 738b4d69701a9d4b232f6a44b340782d096b182b, 1b3adcc2bbc695a0f28f5865a6705e0e59830962, 33cb50761ec12fc0df0e6f99ba97e0d5d4e580fc, a27af00e23a5283e357de1e6bf2a47ebefaa77c2, 5c6236bb0f1fde9140e331c9e1390bb5fccd4f9a
=> spec(backend/NoteCreateService): ローカルユーザーがまだ誰もフォローしていないリモートユーザーによる通知を引き起こす可能性のある投稿を拒否できるように

packages/backend/src/queue/processors/InboxProcessorService.ts
- misskey-dev#13428
- niri-la#153
- niri-la#151
禁止キーワードを含むノートやリモートの通知を引き起こすブロックされた投稿の処理がbullmqによりdelayedに追加される問題を修正しました。
私のサーバーの方でpickさせていただいてましたが、うちの運営がDelayedに追加される問題を見つけてくださったため修正を投げさせていただきました。
無駄に再処理されるため
misskey-dev#13428 では `ContainsProhibitedWordsError`に相当する`IdentifiableError`のidが`689ee33f-f97c-479a-ac49-1b9f8140af99`ですが、IOは独自に`IdentifiableError`に置き換えていたのでそれに合わせてpickしました。
https://github.com/MisskeyIO/misskey/commit/8f57849d91aad4178ec3161da83892e0cf2a056f#diff-44848fc4891ad8cf42ab0d38e74a0797083d5a76591073745c3c259a43693dbeR273
CHANGELOGは独自にメンテされていないようでしたので更新していません。
=> fix: 禁止キーワードを含むノートやリモートの通知を引き起こすブロックされた投稿の処理がDelayed Queueに追加されて再処理される問題

packages/frontend/src/components/MkEmojiPicker.vue
削除されたカスタム絵文字が絵文字ピッカーに残ってるとピッカーを使えなくなる問題を修正
+ カスタム絵文字のカテゴリー判定が壊れてる問題を修正
=> fix(MkEmojiPicker): 削除されたカスタム絵文字が絵文字ピッカーに残ってるとピッカーを使えなくなる問題を修正

packages/frontend/src/components/MkEmojiPicker.vue, packages/frontend/src/components/MkGoogle.vue, packages/frontend/src/pages/admin/files.vue, packages/frontend/src/pages/admin/roles.editor.vue, packages/frontend/src/pages/admin/roles.vue, packages/frontend/src/pages/channels.vue, packages/frontend/src/pages/custom-emojis-manager.vue, packages/frontend/src/pages/search.note.vue, packages/frontend/src/pages/search.user.vue
Chromeのバグでtype=searchのinputボックスを全てパスワードフィールド扱いにしているので一旦type=textに
=> fix(frontend): Chromeのパスワードマネージャーのバグの回避

packages/frontend/src/components/MkGoogle.vue
https://github.com/MisskeyIO/misskey/pull/482 で高さが変わっちゃった
=> fix(frontend): MFMのグーグル検索ボックスの高さがおかしい問題を修正

packages/frontend/src/scripts/search-emoji.ts
=> fix(frontend/search-emoji): Unicodeの絵文字と同じ名前のカスタム絵文字がMkAutocompleteなどで表示されない問題を修正

packages/frontend/src/components/MkEmojiPicker.vue, packages/frontend/src/components/MkReactionsViewer.reaction.vue, packages/frontend/src/scripts/check-reaction-permissions.ts, packages/frontend/src/scripts/emojilist.ts
This reverts commit e3dd3f6b63efffde6dd125e8ecef66aa7069c1a0 partially.
=> fix(frontend): MkEmojiPickerとMkReactionsViewerで一部のUnicode絵文字を正常に扱えない問題を修正

packages/backend/src/core/RemoteUserResolveService.ts, packages/backend/src/core/activitypub/ApRendererService.ts, packages/backend/src/core/activitypub/models/ApNoteService.ts, packages/backend/src/core/activitypub/models/ApPersonService.ts, packages/backend/src/core/activitypub/models/ApQuestionService.ts
リモートのドメインがローカルのドメインから始まっている場合、前方一致のためリモートユーザーが生成できなかったため
=> fix(backend): APのURIがローカルかどうかをoriginで比較するように修正

packages/frontend/src/pages/note.vue
上下逆になっている
多分次の投稿・前の投稿のボタンの位置を上下入れ替えた時消し忘れたんじゃないかな
cc: @syuilo
=> fix(frontend): ノートの詳細ページのユーザーもしくはチャンネルを遡るとタイムラインの並び順番が逆になる問題を修正

packages/frontend/src/components/MkDateSeparatedList.vue, packages/frontend/src/components/MkPagination.vue, packages/frontend/src/pages/note.vue
https://github.com/misskey-dev/misskey/pull/13585
=> enhance: MisskeyIO#529 の追加修正

packages/backend/src/config.ts, packages/backend/src/server/api/ApiCallService.ts
設定ファイルにこんな感じで書く
```
bypassRateLimit:
- header: x-mio-rule-test
value: test
```
=> spec(backend): APIのレートリミットをバイパスできるように

packages/backend/src/config.ts, packages/backend/src/core/activitypub/ApRendererService.ts, packages/backend/src/core/activitypub/models/ApPersonService.ts, packages/backend/src/core/entities/DriveFileEntityService.ts, packages/backend/src/server/api/endpoints/i/update.ts
=> enhance(backend): 内部用と外部（ActivityPub）用で違うアセットドメインが使えるようにする

packages/backend/src/core/UserSuspendService.ts
アカウント削除APIを叩くとheap limit Allocation failed - JavaScript heap out of memoryエラーが出る
followingテーブルの全てのデータをfetchしてnode.js側で全部メモリに載せようとしているため
cc: @syuilo
=> fix(backend/UserSuspendService): 凍結・解凍の処理でfollowingテーブルの全てのデータをfetchしてしまいOOMになる問題を修正

packages/frontend/src/components/MkPostForm.vue, packages/frontend/src/components/MkPostFormDialog.vue
Fix: #601
ノートを投稿後サーバーからAPIが返ってくる前にモーダルを閉じ、
投稿時にエラーが発生した際に投稿モーダルを開き直すように。
=> enhance(frontend/MkPostForm): ノートの投稿後すぐに投稿モーダルを閉じるように

packages/backend/src/server/api/endpoints/i/update-email.ts
=> fix(backend): 登録にメール認証が必須になっている場合、登録されているメールアドレスを削除できないように

packages/frontend/src/pages/emoji-edit-dialog.vue
カスタム絵文字編集画面にてファイルを上げ直しても名前が書き換わらないようになります。
新しくカスタム絵文字を作成する場合等、名前が空の状態の時のみファイルを上げた時に名前が自動で書き換わるようになります。
=> enhance(frontend): カスタム絵文字管理画面にてファイル更新で勝手に名前が変わらないように

packages/frontend/src/ui/_common_/navbar.vue
=> fix(frontend/ui/navbar): kawaiiモード時のロゴの表示を修正

locales/index.d.ts, locales/ja-JP.yml, packages/frontend/src/components/MkUserSetupDialog.Profile.vue, packages/frontend/src/components/MkUserSetupDialog.vue
- アカウント作成後のチュートリアルにBotフラグの設定を追加
- Bot管理者の設定も可能にした (ユーザー選択後、自己紹介文にテンプレ追記)
- チュートリアルをスキップ不可に (イベントハンドラ解除)
- 留意事項: なるべくベース部分を改変しない方向で実装したのでダイアログの閉じるボタンは残っている。<br>バグと誤解されないようにするため、やはりMkModalWindowに手を加える必要がある？
=> feat(frontend): チュートリアルにBotの設定を追加、チュートリアルをスキップ不可に

packages/backend/package.json, packages/backend/src/GlobalModule.ts, packages/backend/src/config.ts, packages/backend/src/core/SearchService.ts, packages/backend/src/di-symbols.ts, pnpm-lock.yaml
ElasticSearchで検索できるようにしました
Closes #502
=> feat(backend): elasticsearchで検索できるように

locales/en-US.yml, locales/index.d.ts, locales/ja-JP.yml, locales/ko-KR.yml, packages/frontend/src/pages/settings/profile.vue
=> enhance(profile): 相互リンク機能の設定画面のデザイン修正

packages/backend/src/server/api/endpoints/admin/roles/update-default-policies.ts, packages/frontend/src/pages/admin/roles.editor.vue, packages/frontend/src/pages/admin/roles.vue
fix(policies): ベースロールのポリシー変更時モデレーションログが残るように
+ canUseReactionのポリシーエディタでの位置変更・ベースロールに設定項目追加
=> fix(policies): ベースロールのポリシー変更時モデレーションログが残るように

packages/backend/src/core/ClipService.ts, packages/backend/src/core/UserSuspendService.ts
- クリップのノート数の上限を超えている際にノートのメニューからクリップ解除できない問題を修正
- TooManyClipNotesError と ClipNotesLimitExceededError の順番を入れ替え
- 凍結されたユーザー自身のアンテナ、ウェブフック、リスト、クリップを消す
- 凍結されたユーザーが含まれているすべてのリストから凍結されてるユーザーを外す
- 凍結されたユーザーのノートをすべてのクリップから消す
=> fix(backend): クリップ周りの不具合修正

packages/backend/src/core/SearchService.ts
ノートが削除された際にちゃんとelasticsearchのindexを削除するようにした。
=> fix(search): elasticsearchに登録されたノートが削除された場合にunindexされないのを修正

packages/backend/src/core/NoteCreateService.ts, packages/backend/src/misc/collapsed-queue.ts, packages/backend/src/queue/processors/InboxProcessorService.ts
シャットダウン時に遅延されていたジョブを全部実行するようにします。
シャットダウン時に遅延されていたジョブを実行しないと notesCount の増分などが失われます。
また、テスト実行でもタイミングがズレて壊れるので、必要な対応です: https://github.com/misskey-dev/misskey/pull/14558#issuecomment-2352626249
=> Perform deferred jobs on shutdown

packages/frontend/src/components/MkEmojiPicker.vue, packages/frontend/src/components/MkNotification.vue, packages/frontend/src/components/MkReactionTooltip.vue, packages/frontend/src/components/MkReactionsViewer.details.vue, packages/frontend/src/pages/custom-emojis-manager.vue
MkReactionsViewer.details.vue
MkReactionTooltip.vue
MkNotification.vue
MkEmojiPicker.vue
custom-emojis-manager.vue
=> fix(frontend): 絵文字関連のスタイルが崩れていたのを修正

packages/backend/src/core/QueueService.ts, packages/backend/src/core/UserSuspendService.ts, packages/backend/src/queue/QueueProcessorModule.ts, packages/backend/src/queue/QueueProcessorService.ts, packages/backend/src/queue/processors/DeleteAccountProcessorService.ts, packages/backend/src/queue/processors/UserSuspendProcessorService.ts, packages/backend/src/queue/types.ts
わりと処理が重くてprimaryで動かすには無理がありそう＆timeoutでキャンセルされてしまってる
=> enhance(backend): 凍結の後処理をQueueで処理するように

packages/backend/src/core/chart/charts/per-user-pv.ts, packages/backend/src/core/chart/core.ts, packages/backend/src/server/api/endpoints/users.ts
=> fix(api/users): ページビューのデータの取得範囲が狭すぎる問題を修正

packages/backend/src/server/api/SigninApiService.ts, packages/frontend/src/components/MkCaptcha.vue, packages/frontend/src/components/MkSignin.vue, packages/frontend/src/components/MkSignupDialog.form.vue
=> enhance: require captcha for signin

packages/frontend/src/components/global/MkCustomEmoji.vue
1. カスタム絵文字の画像が取得できなくなった場合のフォールバック先を画像にしました。
2. カスタム絵文字を読み込む際、一度でも画像の取得に失敗するとerroredフラグが立つとフラグを折ることができない問題を修正しました。
1. 文字だとレイアウトが崩れるため。
2. 普通にバグな気がするため。
=> Enhance: 絵文字のフォールバック先を文字じゃなくて画像に

packages/frontend/src/components/MkNoteDetailed.vue, packages/frontend/src/pages/settings/mute-block.vue
=> fix(frontend/reactions): ローカルのカスタム絵文字のミュートが正常に機能しない問題を修正

packages/frontend/src/components/MkNoteDetailed.vue
=> fix(frontend/reaction): リアクションのミュートのボタンのアイコンが逆になっている問題を修正

packages/frontend/src/components/MkUserSetupDialog.vue, packages/frontend/src/pages/explore.users.vue
=> spec(frontend): みつけるに表示される項目の調整

packages/frontend/src/pages/auth.vue, packages/frontend/src/pages/miauth.vue
Fixes [https://github.com/MisskeyIO/misskey/security/code-scanning/25](https://github.com/MisskeyIO/misskey/security/code-scanning/25)
Fixes [https://github.com/MisskeyIO/misskey/security/code-scanning/26](https://github.com/MisskeyIO/misskey/security/code-scanning/26)
To fix the problem, we need to extend the URL scheme check to include the `vbscript:` scheme. This involves modifying the conditional statement that checks the URL protocol to also consider `vbscript:` as an invalid scheme. This change should be made in the `onAccept` function where the URL validation occurs.
_Suggested fixes powered by Copilot Autofix. Review carefully before merging._
=> Fix code scanning alert no. 25: Incomplete URL scheme check

packages/backend/src/misc/sql-like-escape.ts
Fixes [https://github.com/MisskeyIO/misskey/security/code-scanning/28](https://github.com/MisskeyIO/misskey/security/code-scanning/28)
To fix the problem, we need to modify the `sqlLikeEscape` function to escape backslashes in addition to the existing meta-characters (`%` and `_`). This can be achieved by using a regular expression that matches backslashes and the existing meta-characters, and replacing them with their escaped versions. Specifically, we should replace each backslash with a double backslash and each meta-character with a backslash followed by the character.
_Suggested fixes powered by Copilot Autofix. Review carefully before merging._
=> Fix code scanning alert no. 28: Incomplete string escaping or encoding

packages/frontend/src/scripts/sound.ts
Fixes [https://github.com/MisskeyIO/misskey/security/code-scanning/27](https://github.com/MisskeyIO/misskey/security/code-scanning/27)
To fix this issue, we need to ensure that the `file` variable is properly sanitized before being used as the `src` attribute of the `audio` element. One effective way to do this is by using a URL validation function to ensure that the `file` variable is a valid and safe URL. This will prevent any malicious content from being interpreted as HTML.
1. Create a URL validation function to check if the `file` variable is a valid URL.
2. Use this validation function before assigning the `file` variable to the `src` attribute of the `audio` element.
3. If the `file` variable is not a valid URL, handle the error appropriately (e.g., by rejecting the promise or …
=> Fix code scanning alert no. 27: DOM text reinterpreted as HTML

packages/frontend/src/pages/admin-user.vue
=> スマホで表示した時にipv6だとはみ出てしまうのを修正

packages/backend/src/server/api/endpoints/meta.ts, packages/backend/src/server/api/endpoints/stats.ts, packages/backend/src/server/web/boot.js, packages/frontend/src/boot/common.ts, packages/frontend/src/components/MkVisitorDashboard.ActiveUsersChart.vue, packages/frontend/src/components/MkVisitorDashboard.vue, packages/frontend/src/instance.ts, packages/frontend/src/pages/about.vue, packages/frontend/src/pages/admin/overview.stats.vue, packages/frontend/src/scripts/misskey-api.ts, packages/misskey-js/src/autogen/types.ts
=> spec(api): 一部APIをGETに対応・認証情報をヘッダーに

.devcontainer/docker-compose.yml, .github/workflows/test-backend.yml, chart/templates/Deployment.yml, docker-compose.local-db.yml, docker-compose_example.yml, packages/backend/src/config.ts, packages/backend/src/core/QueueModule.ts, packages/backend/src/queue/QueueProcessorService.ts, packages/backend/src/queue/const.ts, packages/backend/src/server/web/ClientServerService.ts, packages/backend/test/docker-compose.yml
https://www.dragonflydb.io/docs/integrations/bullmq#using-hashtags--optimized-configurations
すべてをロックしてほしくないので
Dragonfly の起動フラグに `--lock_on_hashtags` を付ける必要がある。
上記のドキュメントでは `--cluster_mode=emulated` も付けているが、これは https://redirect.github.com/dragonflydb/dragonfly/pull/2443 で1.14.0以降は不要になった
次のリリース後、これだけマージしてリリースしたい
=> BullMQ + DragonflyDB で Hashtag を使用しすべてをロックしないようにする

packages/backend/src/server/ActivityPubServerService.ts
=> fix(backend/ActivityPubServerService): apOrHtml Constraintが正しく評価されない問題を修正

packages/frontend/src/components/MkPostForm.vue
=> fix(frontend): 一定の条件でノート送信ボタンが意図しない見た目になる問題を修正

packages/frontend/src/components/MkNote.vue, packages/frontend/src/components/MkNotification.vue
コメントに書いてあったものはautoキーワードでなんとかなりそう
misskey-dev@2190092de6409c5dbb02a042d98918580171f4c2
misskey-dev@64bbce4cf4f6d17c7d3309968d95815f177d9544
=> perf(frontend/css): MkNote 及び MkNotification に content-visibility を適用

locales/en-US.yml, locales/index.d.ts, locales/ja-JP.yml, locales/ko-KR.yml, packages/frontend/src/components/MkPostForm.vue
=> chore(frontend): 通報のカテゴリの調整・投稿フォームのガイドラインへの導線に利用規約も追加

packages/frontend/src/components/MkAudioVisualizer.vue
=> fix(frontend/MkAudioVisualizer): ブラウザではなく要素のリサイズイベントに反応するように

packages/frontend/src/pages/admin/ads.vue
=> feat(frontend/admin/ads): 広告のIDを確認できるように

packages/backend/src/core/entities/DriveFileEntityService.ts, packages/backend/src/misc/prelude/url.ts, packages/backend/src/server/FileServerService.ts, packages/backend/src/server/ServerService.ts, packages/backend/src/server/web/UrlPreviewService.ts, packages/frontend/src/scripts/media-proxy.ts, packages/frontend/src/scripts/url.ts
=> spec(MisskeyIO#922): 'https://'を省略するように
